sys-apps/systemd/systemd-218-r2.ebuild, sys-apps/systemd/systemd-9999.ebuild
While moving from systemd-sysv-utils to systemd w/ USE=sysv-utils I
forgot that USE=symlink-usr needed special handling to ensure the
symlinks were created correctly.
=> systemd: copy symlink-usr handling from old systemd-sysv-utils ebuild

profiles/coreos/base/package.accept_keywords
We aren't ready to bump to go1.4 due to a docker-related issue. docker is failing with:
```
Jan 02 01:49:42 ip-10-81-162-79.ec2.internal dockerd[682]: SQL error or missing database: cannot start a transaction within a transaction
```
Maybe related: https://github.com/docker/docker/pull/9615/files#r22109378
This PR is a straight revert of 3e2bf774b501e7fb4363286663b50d77c3a7bf45
=> profiles: revert go to 1.3

eclass/coreos-kernel.eclass
Apparently didn't recompile enough stuff to test the ccache change. From
the ccache 3.2 release notes:
ccache no longer passes preprocessor options like -D and -I to the
compiler when compiling preprocessed output. This fixes warnings
emitted by clang.
The hardened compiler, at least as of gcc-4.8.3, uses -D__KERNEL__ to
detect kernel compiles and in that case avoids enabling PIE by default.
Mixing PIE and kernel compiles can lead to the following error:
error: code model kernel does not support PIC mode
Upstream bug: https://bugs.gentoo.org/show_bug.cgi?id=535984
=> coreos-kernel: Fix kernel builds, broken by update to ccache 3.2.1

sys-apps/systemd/files/218-0001-networkd-accept-a-trailing-.-on-the-end-of-domains.patch, sys-apps/systemd/systemd-218-r3.ebuild
GCE includes the BIND-ism trailing '.' at the end of the domain name
reported in DHCP leases. After 215 systemd started rejecting this.
Fixes a regression compared to the current CoreOS stable release.
Fixes https://github.com/coreos/bugs/issues/220
=> systemd: Accept DHCP domains with a trailing dot

profiles/coreos/base/package.accept_keywords
Machines with glibc-2.17 had trouble upgrading to a build with glibc-2.19.
```
/tmp/au_postint_mount.M1lgpn/bin/cgpt: relocation error: /tmp/au_postint_mount.M1lgpn/lib/libc.so.6: symbol _dl_find_dso_for_object, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```
Let's roll this back to 2.17 for now.
=> profiles: use glibc-2.17 for now

sys-apps/systemd/files/218-0002-allow-module-loading.patch, sys-apps/systemd/systemd-218-r4.ebuild
http://cgit.freedesktop.org/systemd/systemd/commit/?id=d0a0ccf3fecdb422d3fb7ab89646fe9042f11acd
Addresses https://github.com/coreos/bugs/issues/260.
=> sys-apps/systemd: add patch for nspawn module load

sys-apps/systemd/files/218-0003-core-open-up-DefaultDependencies-property-for-transi.patch, sys-apps/systemd/systemd-218-r5.ebuild
Part of fixing https://github.com/coreos/bugs/issues/186
=> systemd: backport patch for DefaultDependencies on transient units

app-emulation/wa-linux-agent/wa-linux-agent-2.0.11-r2.ebuild
The SSH patch wasn't actually being applied because the ebuild silently
failed with "epatch: command not found".
=> app-emulation/waagent: correct ebuild

profiles/coreos/base/package.use
This will allow journald to compress the journal. More interestingly, it will give journalctl the ability to read both COMPRESSED-XZ and non-compressed journals. This is useful if you want to read, for example, a Fedora 21 journal from CoreOS.
=> profiles: enable lzma on systemd

net-libs/libtirpc/libtirpc-0.2.5-r1.ebuild
working toward coreos/bugs#147.
=> net-libs/libtirpc: move netconfig file into /usr

sys-apps/coreutils/coreutils-8.20-r102.ebuild, sys-apps/coreutils/coreutils-8.23-r1.ebuild
unfortunately, dircolors(1) is still installed in /usr/bin, but this is one less file in /etc.
=> sys-apps/coreutils: dont copy DIR_COLORS into etc

app-admin/flannel/files/flanneld.service
See https://github.com/coreos/coreos-overlay/pull/1124#discussion_r25737006
ping @marineam
=> app-admin/flannel: lower file descriptor limit

eclass/cros-workon.eclass
The cros-workon eclass was a mix of all sorts of magic tricks from
ChromeOS but the only ones we care about are the abilities to clone from
local git repos and manage live ebuilds. Many of the extra config
options are unused now in CoreOS and the whole "common.mk" build system
is completely irrelevant. Gutting it all will hopefully make problems we
encounter with it easier to understand.
Also, by moving from the git-2 to the git-r3 eclass for fetching remote
repositories we can use the new EGIT_CLONE_TYPE=mirror option to fetch
all refs of remote repositories, hopefully avoiding the difficulty of
managing packages with multiple development branches like systemd.
=> eclass: strip down cros-workon, switch to git-r3

coreos-base/oem-azure/files/cloud-config.yml, coreos-base/oem-cloudsigma/files/cloud-config.yml, coreos-base/oem-ec2-compat/files/cloud-config.yml, coreos-base/oem-rackspace/files/cloud-config.yml
Use coreos.units instead of write_files for writing the etcd dropins.
Clean up the indentation of the config.
=> coreos-base/oem-*: clean up OEM cloud-configs

coreos-base/oem-gce/files/cloud-config.yml
The command `gcloud preview docker` requires access to the host system docker.
I will create a PR at https://github.com/GoogleCloudPlatform/cloud-sdk-docker to add docker to the container.
See https://github.com/GeertJohan/dockerfiles/tree/master/google-cloud-sdk-with-docker for more information.
=> oem-gce: bind-mount /var/run/docker.sock to gcloud container

profiles/coreos/targets/sdk/package.use.mask
The hardened and sanitizer options are masked on arm64 so the arm64
cross compiler should also not enable them instead of inheriting the
amd64 default to enable them. Fixes building cross gcc.
=> profiles: mask cross compiler flags that are masked on target

profiles/coreos/base/make.defaults
May be useful to people working on CoreOS arm64 support. :)
=> profiles: enable arm64 QEMU target

profiles/coreos/base/package.accept_keywords
=> profiles: use curl 7.41 or greater to pull in ipv4/ipv6 connection fixes

profiles/coreos/targets/generic/package.provided
Upstream has renamed the eselect modules, add the new names in
preparation for updating portage-stable.
=> profiles: add new eselect package names to package.provided

sys-apps/systemd/systemd-9999.ebuild
fixes live ebuild by disabling gnuefi in configure script
=> sys-apps/systemd: add gnuefi use from upstream ebuild

coreos/scripts/config_wrapper
The wrapper for `foo-config` style scripts updated `$PATH` so it could
call the real script by name instead of full path. However this means
that calls to shell utilities like `sed` may use the board's version
instead of the build host's. This hasn't been a problem in the past
because the board and host happened to be compatible but this may not
always be true.
Alternatively the call to sed in this script could be fixed while path is left as-is. This is what https://github.com/coreos/coreos-overlay/pull/1216 proposed. After a quick review of the config scripts involved it looks like some make calls to cat and sed themselves while none of them derive too much meaning from the script name in $0 so calling by absolute path appears to be the safest.
=> scripts: do not include board binaries in $PATH

profiles/coreos/base/package.mask
Fails when binhost reports a 404:
!! Error fetching binhost package info from 'http://builds.developer.core-os.net/sdk/amd64/668.0.0/pkgs/'
Traceback (most recent call last):
File "/usr/lib/python-exec/python2.7/emerge", line 50, in <module>
retval = emerge_main()
File "/usr/lib64/python2.7/site-packages/_emerge/main.py", line 1154, in emerge_main
return run_action(emerge_config)
File "/usr/lib64/python2.7/site-packages/_emerge/actions.py", line 2818, in run_action
getbinpkgs="--getbinpkg" in emerge_config.opts)
File "/usr/lib64/python2.7/site-packages/portage/dbapi/bintree.py", line 633, in populate
self._populate(getbinpkgs)
File "/usr/lib64/python2.7/site-packages/portage/dbapi/bintree.py", line 1034, in _populate
_encodings["stdio"], errors="replace"))
TypeError: coercing to Unicode: …
=> profiles: mask new broken portage

dev-lang/spidermonkey/spidermonkey-17.0.0-r4.ebuild
Mixing `local` and `|| die` will never work because the exit status
being tested is that of local, not any subcommands that may be involved.
=> spidermonkey: fix improper error handling

coreos-base/oem-ec2-compat/files/grub-ec2.cfg, coreos-base/oem-ec2-compat/oem-ec2-compat-0.0.3-r2.ebuild
To complete the fix started in 480fb78, we ban xen_fbfront from loading on EC2.
Testing missed a case where this would still happen.
(Testing this fix now.)
=> oem-ec2-compat: blacklist xen_fbfront

app-admin/flannel/flannel-9999.ebuild, app-admin/toolbox/toolbox-9999.ebuild, app-emulation/docker/docker-9999.ebuild, coreos-base/coreos-au-key/coreos-au-key-0.0.2.ebuild, coreos-base/coreos-dev/coreos-dev-0.1.0.ebuild, coreos-base/coreos-experimental/coreos-experimental-0.0.1.ebuild, coreos-base/coreos-init/coreos-init-9999.ebuild, coreos-base/coreos/coreos-0.0.1.ebuild, coreos-base/gmerge/gmerge-9999.ebuild, coreos-base/libchrome/libchrome-180609.ebuild, coreos-devel/board-packages/board-packages-0.0.1.ebuild, dev-libs/libdivsufsort/libdivsufsort-2.0.1-r1.ebuild, dev-libs/libdnet/libdnet-1.12.ebuild, dev-libs/libmspack/libmspack-0.4_alpha.ebuild, dev-util/bsdiff/bsdiff-4.3-r5.ebuild, dev-vcs/repo/repo-1.21.ebuild, sys-apps/rootdev/rootdev-0.0.1-r11.ebuild, sys-apps/rootdev/rootdev-9999.ebuild, sys-apps/seismograph/seismograph-9999.ebuild, sys-kernel/bootengine/bootengine-9999.ebuild, sys-kernel/coreos-firmware/coreos-firmware-99999999.ebuild, sys-libs/nss-usrfiles/nss-usrfiles-9999.ebuild, sys-process/ktop/ktop-0.0.1-r17.ebuild, sys-process/ktop/ktop-9999.ebuild, virtual/linux-sources/linux-sources-2-r1.ebuild
Add the arm64 keyword to any ebuilds that need it.
=> coreos-overlay: Add arm64 keywords

profiles/coreos/base/package.accept_keywords
Sync package.accept_keywords with  portage-stable btrfs-progs updates at PR https://github.com/coreos/portage-stable/pull/227
This also removes a mention of =sys-fs/btrfs-progs-3.14_pre20140414, which seems to be a stale entry.
=> profile: Update to sys-fs/btrfs-progs-3.17.3

app-emulation/docker/files/docker.service
docker 1.6 seems to ignore TMPDIR and puts tmp files into /var/lib/docker/tmp/
=> replace TMPDIR with DOCKER_TMPDIR

profiles/coreos/base/package.accept_keywords
The update of the elfutils package for arm64 https://github.com/coreos/portage-stable/pull/232 bumped the amd64 stable to elfutils-0.158 which unfortunatly, has a cross compile bug.  Specify the
unstable ~amd64 (elfutils-0.161) to work around the problem.
=> dev-libs/elfutils: Fix compile error with stable

app-admin/setools/setools-3.3.8-r7.ebuild, coreos/config/env/app-admin/setools, sec-policy/selinux-base/selinux-base-2.20141203-r5.ebuild, sys-apps/policycoreutils/policycoreutils-2.4.ebuild
There were a couple of build failures due to selinux packages accidentally
relying on host packages.
=> Add selinux build fixes

eclass/coreos-kernel.eclass, sys-kernel/coreos-kernel/coreos-kernel-4.0.7-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.0.7-r1.ebuild
We will be carrying some patches so the version of the source code will
no longer be simply the upstream mainline version. A -coreos or
-coreos-r1 and so forth will be appended. A new variable defining the
source revision (e.g. -r1) has been added so we can continue to bump the
coreos-kernel revision independently of coreos-sources for minor things
like config updates.
Required for https://github.com/coreos/coreos-overlay/pull/1326
=> coreos-kernel: prepare for using patched kernels

sys-apps/policycoreutils/policycoreutils-2.4.ebuild
There was still some python leaking into this - skip building sepolicy
to avoid issues with cross-compilation.
=> Fix policycoreutils build

eclass/selinux-policy-2.eclass, sec-policy/selinux-base-policy/selinux-base-policy-2.20141203-r5.ebuild, sec-policy/selinux-base/selinux-base-2.20141203-r5.ebuild
SELinux policies were attempting to run the host checkmodule and semodule
commands. The former is easy to fix via pointing them at the build root, the
latter we skip entirely because we don't want to install the policy at this
point - we'll do that during image build.
=> Remove calls to host tools during selinux policy build

coreos-base/oem-exoscale/files/cloud-config.yml, coreos-base/oem-exoscale/files/exoscale-setup-network, coreos-base/oem-exoscale/oem-exoscale-0.0.2.ebuild
As planned, this workaround is not needed anymore for CoreOS
=> exoscale network workaround not needed anymore

sys-apps/systemd/systemd-9999.ebuild
=> sys-apps/systemd: enable nat use flag for ip masquerading in networkd

eclass/coreos-kernel.eclass, profiles/coreos/base/make.defaults, profiles/coreos/base/package.accept_keywords, profiles/coreos/targets/generic/make.defaults, profiles/coreos/targets/sdk/make.defaults, sys-apps/systemd/systemd-9999.ebuild
Kernels are now zillions times happier with ccache. systemd is improved some, the majority of its cpu time is now stuck in lto (a good thing, cuts down on systemd binary sizes a lot) and libtool (ugg, seriously shell is a terrible language to write low level tools in).
Depends on https://github.com/coreos/portage-stable/pull/236
=> ccache and systemd build cleanups

sys-apps/systemd/systemd-9999.ebuild
Dug more into the build process and python is not strictly required for
man pages, it is only used to create an index which isn't significant.
Only call setup_python when features that *do* need python are enabled.
Fixes bootstrap_sdk which builds systemd with minimal use flags.
=> systemd: revise python dependencies

profiles/coreos/base/package.accept_keywords
Depends on https://github.com/coreos/portage-stable/pull/237.
=> profiles: remove unneeded entries for openssl

profiles/coreos/base/make.defaults
By default ccache checks the compiler's mtime and size but that gets
thrown off by reinstalls, including from binary packages. The
alternative mode reads the compiler binary itself instead. In theory
that may be slower but in reality both modes are effectively the same
speed. ccache will now work under catalyst
=> profiles: use compiler hash for ccache

profiles/coreos/base/package.accept_keywords
Specify vim-7.4.712 and vim-core-7.4.712 in package.accept_keywords
to pickup needed upstream cross-compile fix.
https://bugs.gentoo.org/show_bug.cgi?id=473372
Fix build errors like these:
checking for tgetent()... configure: error: NOT FOUND!
You need to install a terminal library; for example ncurses.
Depends on https://github.com/coreos/portage-stable/pull/241 for vim ebuild updates.
=> coreos-overlay: Use latest vim for cross compile fix

profiles/coreos/base/profile.bashrc
Missed this reference to /usr/local/portage in a recent scripts change:
https://github.com/marineam/coreos-scripts/commit/174a847e362f8a1d05210750eafb6ccb4735f59c
So existing SDKs kept working but newly created SDKs would mysteriously
fail to build some things like cmake and vim. :(
=> profiles: fix path to coreos-overlay

app-emulation/rkt/files/rkt-gc.service
systemd requires the ${var} syntax when embedded in words.
Missed in https://github.com/coreos/coreos-overlay/pull/1378
=> rkt: fix grace period variable format

sys-apps/ignition/files/ignition.target
This relies on https://github.com/coreos/bootengine/pull/52 introducing systemd-networkd to the initramfs.
=> ignition: add dependency on systemd-networkd.service

sys-process/ktop/files/ktop-arm64-syscall-fixes.diff, sys-process/ktop/ktop-0.0.1-r18.ebuild
Sync with latest and add arm64 build fix.
=> coreos-overlay: Update ktop for arm64

coreos/config/env/app-editors/vim
Commit 5c4e74c68c3262ee35bd039d94b0237df7381888 (profiles: Use latest vim for
cross compile fix) updated vim to vim-7.4.712, which outdates this local fix.
=> coreos/config: Remove outdated vim fix

sys-fs/xfsprogs/files/xfsprogs-3.1.11-sharedlibs.patch
Commit dda187651d4c10687fadb27eba27e89d38c26b65 (sys-fs/xfsprogs: Move
from portage-stable) did not include a patch needed for xfsprogs-3.2.1.
Fixes build errore like these:
Cannot find $EPATCH_SOURCE!
sys-fs/xfsprogs/files/xfsprogs-3.1.11-sharedlibs.patch
=> sys-fs/xfsprogs: Add Missing patch file

dev-vcs/subversion/subversion-1.8.13-r3.ebuild
When moving this ebuild from portage-stable KEYWORDS was left all ~arch,
breaking the SDK build when the ebuilds were removed from
portage-stable.
=> subversion: set stable keywords

profiles/coreos/base/make.defaults
Enable building arm64 qemu user mode emulation (qemu-aarch64) in
the SDK to allow for running target utilities like ldconfig during
the image build stage.
=> coreos-overlay Enable qemu user mode emulation

profiles/coreos/base/profile.bashrc
This reverts commit 8259b77fc8eba8cfda54da565882283953bfd61a.
Somehow this is breaking the qemu build. Unknown why yet.
=> Revert "profiles: tell ccache to rewrite paths relative to $S"

sys-apps/ignition/files/ignition-disks.service, sys-apps/ignition/files/ignition-files.service, sys-apps/ignition/files/ignition.target
Explicitly order ignition-disks after the network units, and switch
from Requires to Wants in so ignition can still function without them.
=> sys-apps/ignition: move network depdencies to ignition-disks.service

profiles/coreos/targets/generic/make.defaults
We don't use this for anything, but Ansible won't run if it's present and
the selinux python bindings aren't.
Fixes https://github.com/coreos/bugs/issues/449
=> Don't install /sbin/selinuxenabled

sys-apps/ignition/files/ignition-disks.service
There's potential for racing with sgdisk or its generated udev events
which may also open the device if we get scheduled simultaneously.  This
is problematic since ignition-disks may also do partitioning and
formatting of the same devices.
=> sys-apps/ignition: ensure ignition-disks runs after disk-uuid

eclass/coreos-kernel.eclass
The current kernel build process expects ccache to be effective but
since setting CCACHE_BASEDIR globally was reverted in 35d8b34a builds
have been uncached any time the source revision changes.
Until it is safe to set CCACHE_BASEDIR globally again we should at least
make use of it for kernel builds.
=> coreos-kernel: re-enable ccache path rewriting for kernel builds

app-emulation/docker/docker-9999.ebuild
Commit 1ef6648b011 got the latest git hash wrong. :(
=> docker: fix git hash

app-emulation/docker/docker-9999.ebuild
Commit 1ef6648b011c9f927e03de735da305376a2493a8 (app-emulation/docker: Update
CROS_WORKON_COMMIT for arm64) set CROS_WORKON_COMMIT to a bad revision.  This
change corrects it.
=> app-emulation/docker: Fix bad WORKON_COMMIT

profiles/coreos/amd64/generic/make.defaults, profiles/coreos/arm64/generic/make.defaults
Commit f066db21 dropped generating debug symbols because at the time we
were never using them. Well we want to use them now. :)
=> profiles: re-enable debug symbols for board packages

sys-kernel/coreos-kernel/coreos-kernel-4.1.6-r2.ebuild, sys-kernel/coreos-sources/coreos-sources-4.1.6-r2.ebuild, sys-kernel/coreos-sources/files/4.1/net-wireless-wl18xx-Add-missing-MODULE_FIRMWARE.patch
Adds missing firmware for the Hikey developer board wireless controller.
Upstream patch from http://patchwork.kernerl.xyz/patch/7114261/
=> coreos-sources: Add wl18xx firmware patch

profiles/coreos/base/package.accept_keywords
We need this version for improved arm64 support and it has worth-while
improvements. None of the 4.9 related bugs in upstream should impact us:
https://bugs.gentoo.org/show_bug.cgi?id=495124
Depends on https://github.com/coreos/portage-stable/pull/264
=> profiles: upgrade to GCC 4.9

profiles/coreos/base/package.accept_keywords
crossdev creates configs under `/etc/portage/package.keywords` like the following:
cross-aarch64-cros-linux-gnu/binutils arm64 -amd64 -~amd64
cross-aarch64-cros-linux-gnu/gcc arm64 -amd64 -~amd64
cross-aarch64-cros-linux-gnu/linux-headers arm64 -amd64 -~amd64
cross-aarch64-cros-linux-gnu/glibc arm64 -amd64 -~amd64
cross-aarch64-cros-linux-gnu/gdb arm64 -amd64 -~amd64
This ensures cross compilers follow the keywords of the target arch
rather than the host arch. Meanwhile in the profile when we omit the
keyword `package.accept_keywords` only ~arch for the host is implied. So
either we would need to configure crossdev to allow ~arch or we just
need to be explicit in the profile. The later is a bit easer.
=> profiles: set explicit ~arch keywords for gcc 4.9 cross compilers

app-emulation/docker/files/dockerd
We missed this back when 4.1 came out, but now here lies a conundrum:
what is docker's behavior if someone has an existing XFS volume? This
isn't a normal setup for us but it is possible someone has done it.
=> RFC: docker: use overlay driver on XFS

app-admin/flannel/files/flanneld.service
The flannel options.env file isn't easily overridden in the default unit. This was an issue in https://github.com/coreos/coreos-kubernetes/pull/42 where the options file is not written via cloud-config at each boot, so we needed to symlink from /etc
Not sure this is the right approach, but ultimately hoping for an easier way to override this setting.
=> flannel: allow env file path to be overridden

profiles/coreos/base/make.defaults
current this turns on pcre for grep, less, swig and wget.
fixes coreos/bugs#906
=> profiles/coreos: enable pcre use flag

app-emulation/docker/files/early-docker.service
Provide the ability to easily use extra docker options via a drop-in when early-docker starts up.
=> Add $DOCKER_OPTS to early-docker.service ExecStart

profiles/coreos/targets/generic/package.use
@mischief @marineam @crawford 
resolves https://github.com/coreos/bugs/issues/919
=> Enabled epoll for libmicrohttpd and systemd-journal-remote

sys-kernel/coreos-kernel/coreos-kernel-4.2.2-r8.ebuild, sys-kernel/coreos-sources/coreos-sources-4.2.2-r2.ebuild, sys-kernel/coreos-sources/files/4.2/0021-switchdev-fix-return-value-of-switchdev_port_fdb_dum.patch, sys-kernel/coreos-sources/files/4.2/0022-net-switchdev-fix-return-code-of-fdb_dump-stub.patch
Fixes https://github.com/coreos/bugs/issues/980
=> sys-kernel/coreos-sources: fix return value of switchdev_port_fdb_dump()

profiles/coreos/arm64/package.accept_keywords
This partially fixes the build for arm64 arch.
etcd and docker still do not build.
=> Fix arm64 build

app-emulation/docker/docker-1.7.1-r6.ebuild
Fix docker 1.7.1 build errors.
Signed-off-by: Geoff Levand <geoff@infradead.org>
=> app-emulation/docker: Set libdm_no_deferred_remove

eclass/coreos-kernel.eclass, sys-kernel/coreos-kernel/coreos-kernel-4.3.0-r2.ebuild, sys-kernel/coreos-sources/coreos-sources-4.3.0-r1.ebuild, sys-kernel/coreos-sources/files/4.3/0022-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
With this changeset one can build a kernel module out-of-tree in a dev
image in the usual fashion:
```
~# cat Makefile
obj-m := noop.o
~# make -C /lib/modules/4.3.0-coreos-r1/build M=$PWD
make: Entering directory '/usr/lib64/modules/4.3.0-coreos-r1/build'
CC [M]  /tmp/noop/noop.o
Building modules, stage 2.
MODPOST 1 modules
CC      /tmp/noop/noop.mod.o
LD [M]  /tmp/noop/noop.ko
make: Leaving directory '/usr/lib64/modules/4.3.0-coreos-r1/build'
~#
```
/lib/modules/$(uname -r)/source is now populated with a stripped source
tree (headers, scripts, Makefiles...), prod images may build out-of-tree
modules by simply bind mounting these directories into a toolchain
container without needing kernel source.
Note that this build directory is being populated from the _actual_
$KBUILD_OUTPUT used in …
=> coreos-kernel: populate /lib/modules/$(uname -r)/build

profiles/coreos/base/package.accept_keywords
https://github.com/coreos/bugs/issues/1017
=> profiles/coreos/base: use openssl 1.0.2e for security fixes

profiles/coreos/base/package.accept_keywords
=> profiles/coreos/base: use btrfs-progs 4.2.2 for fixes and features

eclass/coreos-kernel.eclass
allows the proper operation of 'depmod' when building out-of-tree modules
=> preserve 'System.map' during kernel build

sys-libs/glibc/files/eblits/src_compile.eblit
When bootstrapping glibc installs headers but is not built. However a
native tool, cross-rpcgen, must be built in order to generate rpcsvc
header files. By skipping directly to `make headers-install` the tool
winds up getting built during src_install, building as root instead of
the portage user and so on. Although uncommon this may lead to
permission issues with ccache.
=> glibc: ensure cross-rpcgen is compiled during the compile phase

sys-kernel/coreos-kernel/coreos-kernel-4.3.0-r4.ebuild
This kernel doesn't have the corresponding sources any more.
=> coreos-kernel: prune old ebuild

sys-apps/shadow/files/tmpfiles.d/etc-shadow.conf, sys-apps/shadow/files/tmpfiles.d/var-shadow.conf, sys-apps/shadow/shadow-4.1.5.1-r4.ebuild
This will allow bootengine to only apply the shadow config that applies to /etc.
=> sys-apps/shadow: split shadow.conf

dev-db/etcd/etcd-9999.ebuild
Define a value for CROS_WORKON_COMMIT to avoid build errors when building etcd unstable.
Also, add an equals sign to GO_LDFLAGS to fix build warnings like:
link: warning: option '-X version.GitSHA XXX' may not work in future releases
=> dev-db/etcd: Fix unstable build error

app-admin/flannel/files/flanneld.service
Flannel TLS configuration is kinda confusing... When you would like to configure custom keys path you have to set custom `ETCD_SSL_DIR` environment variable, but the actual path to the keys should be `/etc/ssl/etcd`.
This fix tells docker to use same destination path.
=> Use defined ETCD_SSL_DIR path inside the flannel container

sys-apps/shadow/shadow-4.1.5.1-r5.ebuild
Several cloud providers have requested that the minimum password length be
increased to eight.
=> sys-apps/shadow: increase minimum password length

dev-db/etcd/etcd-9999.ebuild
The current CROS_WORKON_COMMIT of etcd-2.2.4 does not build for
arm64.  Add a temporary conditional to set CROS_WORKON_COMMIT to
a known good revision for arm64.
=> dev-db/etcd: Set CROS_WORKON_COMMIT for arm64

dev-db/etcd/etcd-9999.ebuild
etcd-2.2.5 builds for arm64, so a special conditional for it is no longer needed.
See: https://github.com/coreos/etcd/issues/3623
=> Revert "dev-db/etcd: Set CROS_WORKON_COMMIT for arm64"

eclass/coreos-kernel.eclass
To aid in debugging kernel builds set the kernel make variable
V=1 to get verbose build output when ECLASS_DEBUG_OUTPUT is
set.
=> coreos-kernel: Add verbose build

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
depends on coreos/portage-stable#385
fixes coreos/bugs#455
=> profiles/coreos: accept app-misc/jq-1.5-r1

coreos-base/coreos-cloudinit/coreos-cloudinit-9999.ebuild
This was dropped in 0cf04c447ce67f48f8546d745742ca22e5b8e603.
=> coreos-base/coreos-cloudinit: re-add arm64 keyword

dev-lang/go/go-9999.ebuild, profiles/coreos/base/package.accept_keywords
This ought to be interesting. Let's hold off on merging this until the Alpha is cut.
=> profiles: add go-1.5.3 to accepted keywords

profiles/coreos/targets/generic/prod/make.defaults
But add /usr/lib*/*/include to prevent these headers from sneaking in.
This is being done to retain the kernel headers from
/lib/modules/$(uname -r)/build in production images.
=> profiles: remove *.h from prod INSTALL_MASK

coreos-base/oem-azure/files/grub.cfg, coreos-base/oem-ec2-compat/files/grub-ec2.cfg, coreos-base/oem-gce/files/grub.cfg
This was introduced to assist users in troubleshooting on cloud
providers without an interactive console but with read-only access to
console output.
However, due to how journald implements the forwarding (synchronously)
it can have a dramatic impact on the overall logging performance.
Fixes https://github.com/coreos/bugs/issues/1162
=> coreos-overlay: cease ForwardToConsole in journald

sys-apps/systemd/systemd-225-r13.ebuild
```
cf0d969 networkd: make sure we remove udev fd from epoll *before* closing it
2d7da74 sd-event: improve debug message when we fail to remove and fd from an epoll
```
=> sys-apps/systemd: bump to include recent fixes

sys-apps/systemd/systemd-225-r14.ebuild
```
b1ec77c nspawn: don't try to resolve passed binary before entering namespace
```
Fixes https://github.com/coreos/bugs/issues/1196.
=> sys-apps/systemd: include latest fixes

profiles/coreos/targets/generic/profile.bashrc
This little bit of glue for handling old-style foo-config scripts was
assuming that anything in /usr/bin with a -config suffix was worth
wrapping. This is certainly not the case if the file in question is a
binary. This is most likely to cause confusion with pkg-config.
=> profiles: do not wrap pkg-config as a legacy library config script

profiles/coreos/amd64/generic/package.use
This fixes [#1059](https://github.com/coreos/bugs/issues/1059) allows the selinux context information to be displayed.
Now `ls -Z` shows the correct output. ex:
```
core@coreos_developer_qemu-1010-0-0-2 ~ $ id -Z
system_u:system_r:kernel_t:s0
```
=> coreos/coreos-overlay: build selinux with coreutils

profiles/coreos/arm64/package.accept_keywords, sys-block/open-iscsi/files/iscsid-initiatorname.service, sys-block/open-iscsi/files/iscsid.service, sys-block/open-iscsi/open-iscsi-2.0.873-r2.ebuild, sys-fs/multipath-tools/multipath-tools-0.5.0-r1.ebuild
Generate the initiator name at boot, and fix iscsi builds on ARM
=> iSCSI fixes

profiles/coreos/targets/generic/profile.bashrc
Commit 631890b9 was completely broken and started skipping all *-config
file, not just pkg-config, because I forgot to specify the file path.
=> profiles: fix config script wrappers

sys-fs/multipath-tools/files/multipath-tools-0.5.0-property-whitelist-SCSI_IDENT.patch, sys-fs/multipath-tools/multipath-tools-0.5.0-r2.ebuild
Issue [#1236](https://github.com/coreos/bugs/issues/1236).
=> Include upstream patch to whitelist devices with SCSI_IDENT property

app-emulation/google-compute-daemon/google-compute-daemon-1.1.1-r4.ebuild, app-emulation/google-startup-scripts/google-startup-scripts-1.1.1-r3.ebuild
Broken back in 02c004e846, newly installed GCE images haven't worked
right ever since then. :(
=> google-*: import eutils, fix applying required patches

profiles/coreos/targets/generic/package.use
We don't need the nss utils in the product, so disable the flag.
=> Disable nss utils build

profiles/coreos/base/package.accept_keywords
depends on coreos/portage-stable#415
=> profiles: accept jq ebuild with heap overflow fix

eclass/coreos-kernel.eclass, profiles/coreos/base/profile.bashrc
There are a number of ways the absolute path to a source file can make
it into the compiler output, some of which can prevent cached results
from being used when compiling related code in different locations.
The default source directory $S contains the package version so paths
need to be relative to it in order to work between package versions.
Previously attempted in 8259b77fc8eba8cfda54da565882283953bfd61a, should
be safe now that QEMU has been upgraded to 1.5. I've been using this
setting on my Gentoo machines and haven't found any other issues.
Also reverts commit 661ceb0fa114c499fa99b653bccb6d011c0d0b49.
=> profiles: tell ccache to rewrite paths relative to $S

eclass/coreos-go.eclass
Just the eclass update from https://github.com/coreos/coreos-overlay/pull/1939
=> eclass/coreos-go: add ppc64 and x86 arch to go_get_arch

profiles/coreos/targets/generic/make.defaults
Likely inherited from ChromeOS but even for them it is a completely
ridiculous flag to disable. We had SHA512 enabled pre-PAM since shadow
does not have this use flag so this restores previous behavior.
=> profiles: stop disabling SHA512 password hashes in PAM

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
The newer version is needed for arm64, and need the same version across
all architectures because the build host and target's version must match.
=> profiles: update protobuf from 1.5 to 1.6

profiles/coreos/targets/generic/prod/README, profiles/coreos/targets/generic/prod/package.mask
This serves as a sanity check to avoid mistakes like pulling in python.
=> profile: begin explicitly masking packages for prod images

profiles/coreos/amd64/sdk/package.accept_keywords
qemu-2.6.0 includes a bug fix for arm64.  Without this the 4.6 kernel
will hang early in its boot with qemu-system-aarch64.
Depends on https://github.com/coreos/portage-stable/pull/437
@marineam Is this how we specify an unstable version (~amd64) for the SDK?
=> profiles/sdk: Build unstable qemu

sec-policy/selinux-virt/files/virt.diff
Fix a typo that broke the build
=> sec-policy/selinux-virt: Fix build

profiles/coreos/targets/generic/prod/package.mask, sys-auth/polkit/polkit-0.113-r2.ebuild
polkit's gobject library doesn't actually link against the library
provided by gobject-introspection so this appears to be a build-time
only dependency. Fixing this prunes python and lots of other packages:
```diff
--- developer-1068.0.0+2016-06-15-1524-a1/coreos_production_image_packages.txt	2016-06-15 15:27:59.353348324 -0700
+++ developer-1068.0.0+2016-06-15-1609-a1/coreos_production_image_packages.txt	2016-06-15 16:12:36.694523784 -0700
@@ -1,4 +1,3 @@
-app-admin/eselect-1.4.5::portage-stable
app-admin/flannel-0.5.5-r2::coreos
app-admin/fleet-0.11.7::coreos
app-admin/kubelet-1.1.2_p0-r3::coreos
@@ -6,7 +5,6 @@
app-admin/locksmith-0.3.4-r1::coreos
app-admin/logrotate-3.9.1-r1::portage-stable
app-admin/mayday-0.1.0-r1::coreos
-app-admin/python-updater-0.11::portage-stable …
```
=> sys-auth/polkit: remove gobject-introspection from RDEPEND

profiles/coreos/targets/generic/prod/README, profiles/coreos/targets/generic/prod/package.mask, sys-auth/polkit/polkit-0.113-r2.ebuild
Backport https://github.com/coreos/coreos-overlay/pull/2011 and https://github.com/coreos/coreos-overlay/pull/1999
=> sys-auth/polkit: remove gobject-introspection from RDEPEND for 1068

app-admin/flannel/files/flanneld-rkt.service, app-admin/flannel/flannel-0.5.5-r2.ebuild, app-admin/flannel/flannel-0.5.5-r3.ebuild, app-admin/flannel/flannel-9999.ebuild
Launch flannel with rkt instead of an early instance of docker and remove early-docker
=> flannel: use rkt to launch flannel on amd64

profiles/coreos/arm64/package.accept_keywords
Sync nmap in package.accept.keywords to https://github.com/coreos/portage-stable/pull/452.
Fixes arm64 build breakage.
cc: @mischief
=> profiles/arm64: Update nmap

profiles/coreos/base/package.use, sys-auth/sssd/sssd-1.13.1-r1.ebuild
Add the appropriate flags for building with Kerberos support and bump the version
=> sys-auth/sssd: Enable Kerberos support

profiles/coreos/base/package.use
Enable Kerberos support in openssh, since we're already shipping the libraries
=> profiles/coreos: Turn on Kerberos in ssh

sys-fs/e2fsprogs/metadata.xml
Revert the removal of metadata.xml from commit
cc7f579db2bb8e12011b884623689922bf245998.
Fixes equery errors like these:
!!! Package sys-fs/e2fsprogs-1.42.13-r1 is missing metadata.xml
cc: @ajeddeloh
=> Fix equery for e2fsprogs

profiles/coreos/amd64/generic/package.mask
We need to sort out OEM updating asap...
=> profiles: mask recent procps in amd64 images

sys-auth/sssd/sssd-1.13.1-r2.ebuild
=> Make undefined NSS lookups succeed when SSSD isn't running

profiles/coreos/targets/generic/make.defaults, profiles/coreos/targets/generic/prod/make.defaults
This commit moves some masked entries (mostly autotools binaries)
from common config to the prod profile, so that development packages
are fully functional on dev profile.
=> profiles: only prune development tools on prod

profiles/coreos/base/package.accept_keywords
depends on https://github.com/coreos/portage-stable/pull/466
=> profiles/coreos: accept net-misc/curl-7.50.1

profiles/coreos/base/package.use
Build the SSH-related helpers for sssd so authorized_keys can be stored
in LDAP.
=> sys-auth/sssd: Enable SSH helpers

app-emulation/rkt/rkt-9999.ebuild
After this we're no longer passing -nopie to the linker, rkt is
ending up with a TEXTREL section and SELinux is blocking execution.
Revert until it's fixed.
=> Revert "app-emulation/rkt: Remove go environment settings"

app-emulation/runc/files/0001-Makefile-do-not-install-dependencies-of-target.patch, app-emulation/runc/runc-1.0.0_rc1_p20160615-r1.ebuild
runc invokes go build -i, which installs dependencies to GOROOT. the
build is run without privilege to write there, so it fails.
=> app-emulation/runc: patch out installing deps in makefile

app-emulation/open-vm-tools/open-vm-tools-9.10.0-r1.ebuild, dev-lang/go-bootstrap/go-bootstrap-1.5.3.ebuild, eclass/coreos-kernel.eclass, sys-auth/realmd/realmd-0.16.2.ebuild
I'm tinkering w/ performing builds that make a number of checks portage performs fatal. This would avoid things like missing TEXTREL issues. Before that can happen here are a few minor things to fix up.
=> multilib-strict and stricter fixes

sys-libs/ncurses/files/ncurses-5.9-compiler-warnings.patch, sys-libs/ncurses/ncurses-5.9-r7.ebuild
From http://ncurses.scripts.mit.edu/?p=ncurses.git;a=commit;h=73ab536b636227eed291dad213ca88c93d422fb8
The important part is the tiny change to use the attr_get function
instead of the macro fixing:
test/ncurses.c:1681:29: warning: the comparison will always evaluate
as ‘true’ for the address of ‘old_attr’ will never be NULL [-Waddress]
which causes portage to abort with FEATURES=stricter
=> sys-libs/ncurses: fix some compiler warnings

sys-libs/glibc/files/2.23/glibc-2.23-c-utf8-locale.patch, sys-libs/glibc/files/2.24/glibc-2.24-c-utf8-locale.patch, sys-libs/glibc/glibc-2.21-r5.ebuild
The 2.23 version of the patch is used by Fedora for glibc versions
2.21 through 2.23. Although currently unused by the ebuild the 2.24
version of the patch is included for future reference.
The latest revision can be found here:
http://pkgs.fedoraproject.org/cgit/rpms/glibc.git/tree/glibc-c-utf8-locale.patch
Note: this does not enable C.UTF-8 in images yet, INSTALL_MASK must be adjusted and calling localedef must be added to the image building process. This does enable C.UTF-8 in the SDK though.
=> sys-libs/glibc: import the C.UTF-8 locale from Fedora

profiles/coreos/targets/generic/make.defaults
This data can be later removed by build_image once it has run localedef
to generate the C.UTF-8 locale. When cross-compiling the glibc ebuild
won't run localedef so it is up to build image to handle.
=> profiles: include libc locale data

app-emulation/containerd/containerd-0.2.3-r1.ebuild, app-emulation/containerd/containerd-9999.ebuild, app-emulation/containerd/files/containerd.service, app-emulation/docker/files/docker.service, app-emulation/docker/files/early-docker.service
Reviewers, please think about my associated manual test before approving. These changes continue to propose sharing the same containerd instance between early-docker and "real" docker, which seems to work fine.
Tested by pushing to GCE with the following userdata
```yaml
#cloud-config
write_files:
- path: "/root/dockerize.sh"
permissions: "0755"
owner: "root"
content: |
#!/bin/sh
dependencies() {
echo $1
LIBS_AND_JUNK=$(env -i ldd $1 | awk '{print $0}' RS=' ')
for tok in $LIBS_AND_JUNK; do
if test -f "$tok"; then
echo "$tok"
fi
done
}
dependencies $1 | sort | uniq | tar cv -h -P -T - | docker import - $2
coreos:
etcd2:
discovery: https://discovery.etcd.io/90248cd879bd6ff90eb7be69847573b1
advertise-client-urls: http://$private_ipv4:2379
initial-advertise-peer-urls: …
```
=> app-emulation/{containerd,docker}: separately managed containerd unit

profiles/coreos/arm64/package.accept_keywords
This fixes the nightly Jenkins build failures.
=> profiles: use the same smartmontools version on arm64

dev-lang/spidermonkey/files/spidermonkey-1.8.5-fix-arm64-va-48.patch, dev-lang/spidermonkey/spidermonkey-1.8.5-r5.ebuild
An updated fix for the arm64 48 bit VA problem that causes polkit to crash on arm64.  Fixes arm64 runtime problems like these:  ```polkitd: unhandled level 3 translation fault (11)```
This fix uses the patch from @garygrebus's PR https://github.com/coreos/coreos-overlay/pull/2228, but to avoid the flannel problems the patch introduces on amd64, the patch is conditionally applied to arm64 only.
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1143022 this 48 bit VA problem has been fixed in newer versions of mozjs, but the memory management code of newer versions is very different, and a backport of that fix is not really possible.
Older PRs/comits for this problem:
https://github.com/coreos/coreos-overlay/pull/2241 ```Revert "dev-lang/spidermonkey: Better fix for …
```
=> spidermonkey: Update CONFIG_ARM64_VA_BITS_48 fix

profiles/coreos/arm64/package.accept_keywords
This fixes today's Jenkins build failure.
=> profiles: fix GLSA 201611-17 (rpcbind) on arm64

app-emulation/runc/runc-1.0.0_rc1_p20160615-r2.ebuild
runc needs to have selinux enabled for docker to be confined.
=> app-emu/runc: enable selinux

app-emulation/runc/runc-1.0.0_rc1_p20160615-r3.ebuild, profiles/coreos/amd64/generic/package.use
There's no dependency here - runc does appropriate setup directly, not with
cgo.
=> app-emulation/runc: Drop libselinux rdepend

net-misc/openssh/files/openssh-7.2_p1-fix-krb5-config.patch, net-misc/openssh/openssh-7.2_p2-r1.ebuild
This adds a simple patch to fix cross-compiling OpenSSH.  It has been proposed upstream, and a test Jenkins build is running with it.
=> net-misc/openssh: fix krb5-config detection

profiles/coreos/base/make.defaults, profiles/coreos/targets/generic/make.defaults
The `sys-apps/shadow` package in the SDK depends on `cracklib`.  It is not used by `shadow` in the images, and no other packages are using it.  With this dependency removed, `cracklib` can be dropped from portage-stable.
=> profiles: move USE=-cracklib to base

coreos-base/oem-vagrant/files/box/Vagrantfile
This PR disables guest tools for parallels/vagrant images.
=> oem-vagrant: disable guest tools for parallels

profiles/coreos/amd64/generic/use.mask, profiles/coreos/amd64/package.use.force, profiles/coreos/amd64/usr/parent, profiles/coreos/arm64/package.use.force, profiles/coreos/arm64/use.mask, profiles/coreos/arm64/usr/parent, profiles/coreos/base/make.defaults, profiles/coreos/base/package.use, profiles/coreos/base/package.use.force, profiles/coreos/base/use.mask, profiles/coreos/targets/generic/package.use
The only thing particularly interesting here are the seccomp and xattr flags. Upstream has enabled them by default and it seems fair to follow suit. amd64 already has xatter on all packages and seccomp on some. arm64 is the bigger change as it had both completely disabled. The end result is that the big portage-stable update will not toggle any flags.
All the rest of the churn is just trivial cleanups or tweaks to make diffing emerge results before and after the portage-stable update easier.
=> Profile updates/cleanups in preparation for a portage-stable update

profiles/coreos/arm64/package.accept_keywords
Enabled for squashfs, rpcbind, and unzip. Addresses the following GLSAs:
https://security.gentoo.org/glsa/201612-40
https://security.gentoo.org/glsa/201611-17
https://security.gentoo.org/glsa/201611-01
=> profiles: accept ~arm64 for a few packages

profiles/coreos/targets/generic/prod/make.defaults
=> profiles: drop some Python and Perl scripts from prod images

dev-libs/libgpg-error/libgpg-error-1.24.ebuild, profiles/coreos/arm64/package.accept_keywords
Our `package.accept_keywords` file was becoming a mess.  This starts cleaning it, as part of coreos/portage-stable#518.
=> profiles: start cleaning arm64 package.accept_keywords

profiles/coreos/arm64/package.accept_keywords
This is the cleanup part of coreos/portage-stable#519.
=> profiles: more arm64 package.accept_keywords cleanup

profiles/coreos/arm64/package.accept_keywords
Part of coreos/portage-stable#520.
=> profiles: sync nss and nspr versions on arm64

sys-kernel/coreos-sources/coreos-sources-4.8.17.ebuild, sys-kernel/coreos-sources/files/4.8/z0022-Add-arm64-coreos-verity-hash.patch
Adds a place to inject the verity hash value in the arm64 kernel image.
cc: @mjg59
=> coreos-sources: Add arm64 verity hash

app-emulation/runc/files/0002-Dont-set-label-for-mqueue-under-userns.patch, app-emulation/runc/runc-1.0.0_rc2-r3.ebuild
This fixes a bug in usernamespace support under selinux.
This patch matches the one applied to fedora.
Read more about this exciting tale in: https://github.com/opencontainers/runc/pull/959, https://github.com/projectatomic/runc/commit/3ce50afe04f102cf28dbb6425773011707bf3ae0
cc @crawford
=> app-emulation/runc: workaround userns issue

sys-kernel/coreos-kernel/coreos-kernel-4.8.17-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.8.17-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.8.17-r1.ebuild, sys-kernel/coreos-sources/files/4.8/z0023-selinux-allow-context-mounts-on-tmpfs-ramfs-devpts-within-user-namespaces.patch
Upstream as https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/commit/?id=01593d3299a1cfdb5e08acf95f63ec59dd674906
See also https://github.com/opencontainers/runc/issues/1215
=> sys-kernel/coreos-sources: backport selinux+userns patch

profiles/coreos/arm64/package.accept_keywords
This should fix the squashfs GLSA.  The libpng update isn't committed yet.  I'll get to it shortly, but I don't think this will break anything until then.
=> GLSA syncs

sys-kernel/coreos-kernel/coreos-kernel-4.8.17-r2.ebuild, sys-kernel/coreos-modules/coreos-modules-4.8.17-r2.ebuild, sys-kernel/coreos-sources/coreos-sources-4.8.17-r2.ebuild, sys-kernel/coreos-sources/files/4.8/z0022-Revert-tty-serial-8250-add-CON_CONSDEV-to-flags.patch
Our GRUB config specifies tty0 as the primary console, but it was being forced to the serial port instead. As a result, boot failures produced no visible error messages on tty0, and the emergency shell was likewise inaccessible.
Backports #2417 to beta.
=> sys-kernel/coreos-sources: Stop routing primary console to ttyS0

sys-apps/shadow/files/shadow-4.4-fix-root-defaults.patch, sys-apps/shadow/shadow-4.4-r1.ebuild
This is a backport of shadow-maint/shadow#65.
This fixes coreos/bugs#1787.
=> sys-apps/shadow: load defaults from the chroot

sys-libs/ncurses/ncurses-5.9-r8.ebuild
Every once in a while, I stumble upon this error message because the terminfo for `rxvt-unicode-256color` is missing in CoreOS:
```
WARNING: terminal is not fully functional
-  (press RETURN)
```
`rxvt-unicode` is a quite popular terminal emulator and, at least on [Arch](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rxvt-unicode#n32), compiled with [`--enable-256-color`](http://cvs.schmorp.de/rxvt-unicode/README.configure?view=markup#l240). I figured it's worth a try to get this fix upstream instead of working around this problem over and over again...
=> sys-libs/ncurses: add rxvt-unicode-256color

app-emulation/runc/files/runc-1.0.0_rc2-init-non-dumpable.patch, app-emulation/runc/runc-1.0.0_rc2-r4.ebuild
This re-fixes CVE-2016-9962
Due to reusing the same "${P}" as upstream gentoo and also using their
distfile mirror, the downloaded source tarball was not for the
EGIT_COMMIT referenced in the ebuild, and so did not include the patch.
I've also updated the EGIT_COMMIT to match what's really being used,
though it's still ignored in this change.
The patchfile was taken from gentoo's overlay.
This was done rather than fixing the ebuild to use the intended commit
simply because it ends up being a smaller change. The proper change to
use the commit intended will be done on other channels.
=> app-emulation/runc: re-apply non-dumpable patch

coreos/config/env/sys-devel/gettext
This is only an issue when the glibc versions differ between the SDK and the sysroot.  The M4 library detection functions in gettext do bad things on their own, so bypass them.
=> coreos/config/env: make gettext builds stay inside the sysroot

profiles/coreos/base/package.accept_keywords
This is part of coreos/portage-stable#527.
=> profiles: update GCC to a stable version

profiles/coreos/base/package.use
Build the sudo-related helpers for sssd.
So sudoers can be retrieve from LDAP.
coreos/bugs#1856
=> profiles/coreos: Turn on sudo support in sssd

coreos-base/oem-packet/files/cloud-config.yml, coreos-base/oem-packet/files/reset-interfaces.sh, coreos-base/oem-packet/oem-packet-0.0.5.ebuild
Now that Packet uses Ignition to configure systemd-networkd units
before systemd-networkd starts, the workaround described in the
below issue is no longer necessary:
https://github.com/coreos/bugs/issues/36
=> coreos-overlay/oem-packet: Remove bond workaround

dev-libs/openssl/files/openssl.conf, dev-libs/openssl/openssl-1.0.2k-r1.ebuild
This fixes a few `openssl` commands such as `req` on PXE at least and takes out the sample CA scripts.
Note that this also wipes out `/etc/ssl` in the SDK (aside from `certs`), but I haven't hit any build failures from it yet.  We might want to handle that case at some point anyway.
=> dev-libs/openssl: generate /etc/ssl at boot

app-admin/kubelet-wrapper/files/kubelet-wrapper
The current version of the kubelet-wrapper does not expose the container logs to external utilities like fluentd.
=> Expose container logs out of kubelet-wrapper

coreos-base/oem-hyperv/files/cloud-config.yml, coreos-base/oem-hyperv/files/oem-release, coreos-base/oem-hyperv/oem-hyperv-0.0.3-r1.ebuild
Since there is no cloud-config to drop here, just bring this OEM inline
with the others in terms of their structure.
=> coreos-base/oem-hyperv: switch to ignition scheme

profiles/coreos/base/package.use
Right now iputils is only installing ping.
This fixes coreos/bugs#1572.
=> Install traceroute and arping

dev-libs/openssl/openssl-1.0.2k-r2.ebuild
This fixes the nightly build failure from an `openssl req` call in building the SDK stage4.
=> dev-libs/openssl: package /etc/ssl for SDK bootstrapping

sys-kernel/coreos-kernel/coreos-kernel-4.9.16-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.9.16-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.9.16-r1.ebuild, sys-kernel/coreos-sources/files/4.9/z0001-Add-secure_modules-call.patch, sys-kernel/coreos-sources/files/4.9/z0002-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch, sys-kernel/coreos-sources/files/4.9/z0003-x86-Lock-down-IO-port-access-when-module-security-is.patch, sys-kernel/coreos-sources/files/4.9/z0004-ACPI-Limit-access-to-custom_method.patch, sys-kernel/coreos-sources/files/4.9/z0005-asus-wmi-Restrict-debugfs-interface-when-module-load.patch, sys-kernel/coreos-sources/files/4.9/z0006-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch, sys-kernel/coreos-sources/files/4.9/z0007-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch, sys-kernel/coreos-sources/files/4.9/z0008-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch, sys-kernel/coreos-sources/files/4.9/z0009-x86-Restrict-MSR-access-when-module-loading-is-restr.patch, sys-kernel/coreos-sources/files/4.9/z0010-Add-option-to-automatically-enforce-module-signature.patch, sys-kernel/coreos-sources/files/4.9/z0011-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch, sys-kernel/coreos-sources/files/4.9/z0012-efi-Add-EFI_SECURE_BOOT-bit.patch, sys-kernel/coreos-sources/files/4.9/z0013-hibernate-Disable-in-a-signed-modules-environment.patch, sys-kernel/coreos-sources/files/4.9/z0014-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.9/z0015-Add-arm64-coreos-verity-hash.patch, sys-kernel/coreos-sources/files/4.9/z0016-selinux-allow-context-mounts-on-tmpfs-ramfs-devpts-w.patch, sys-kernel/coreos-sources/files/4.9/z0017-perf-x86-intel-rapl-Make-package-handling-more-robus.patch, sys-kernel/coreos-sources/files/4.9/z0018-perf-x86-intel-uncore-Make-package-handling-more-rob.patch, sys-kernel/coreos-sources/files/4.9/z0019-xfrm_user-validate-XFRM_MSG_NEWAE-XFRMA_REPLAY_ESN_V.patch, sys-kernel/coreos-sources/files/4.9/z0020-xfrm_user-validate-XFRM_MSG_NEWAE-incoming-ESN-size-.patch
For stable.
I'll admit I haven't successfully built this yet due to the wonders of perl in our sdk right now.
=> sys-kernel/coreos-sources: Apply CVE-2017-7184 fix

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/arm64/package.provided
=> profile: Enable arm64 perl

profiles/coreos/arm64/package.accept_keywords
The current stable curl ebuild matches both amd64 and arm64, so drop our old explicit accept_keywords line.
Part of coreos/portage-stable#535.
=> Sync GLSAs

app-admin/kubelet-wrapper/files/kubelet-wrapper
So far `/var/lib/kubelet` was mounted as an implicit non-recursive mount.
This changes the wrapper to an explicit recursive mount.
As shown in https://github.com/kubernetes/kubernetes/issues/38498#issuecomment-282493681,
current non-recursive behavior seems to confuse the kubelet which
is incapable of cleaning up resources for orphaned pods, as the
extisting mountpoints for them are not available inside kubelet
chroot.
With `recursive=true`, those mounts are made available in the
chroot and can be unmounted on the host-side from kubelet chroot
via shared back-propagation.
Fixes https://github.com/coreos/bugs/issues/1831
=> app-admin/kubelet-wrapper: mark kubelet datadir volume as a recursive mount

eclass/cros-workon.eclass
With portage-2.3.3, `failglob` errors are printed when any of these lines expand to `: *`, so quote the variables to not use patterns.
=> eclass: quote cros-workon assignments

app-admin/kubelet-wrapper/files/kubelet-wrapper
This reverts commit 14be7e884c211d222c168daedfc75487f86d4dfb, reversing
changes made to 144812b4f9e5104b09a5122a49933501308a16b9.
See https://github.com/coreos/bugs/issues/1892
Fixing that issue correctly turns out to be more complicated than expected (requiring patching rkt fly), so let's hold this fix out of stable for one more cycle.
It's better to have the state of the world before this (kubelet-wrapper boots, but doesn't have logs plumbed out unless you manually add mounts) than after (kubelet-wrapper fails to boot if you had configured logs).
=> Revert "Merge pull request #2308 from sapcc/master"

coreos-base/oem-packet/oem-packet-0.0.5.ebuild
Currently, we have to run a different branch of the Jenkins scripts to build stable releases so they don't attempt to build Packet images on `arm64`.  I remember @crawford didn't want to backport this when the branch was still in beta, but now that it is in stable, if we apply this and build the image, it will never be published.  So this PR has no user-visible effect, but it cleans up the overhead of us having to remember to use different build procedures.  Any concerns with this @crawford/@euank?
=> Cherry-pick enabling Packet on arm64 for stable

profiles/coreos/arm64/package.accept_keywords
Part of coreos/portage-stable#550.
=> profiles: bump arm64 versions for GLSAs

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/553.
=> profiles: Update btrfs-progs and dosfstools

profiles/coreos/base/package.use
=> profiles: build lz4 support into journald

profiles/coreos/base/package.use
We are already installing `mit-krb5`, this just allows curl to authenticate with it.
=> profiles: enable Negotiate authentication in curl

app-admin/kubelet-wrapper/files/kubelet-wrapper
The `kubenet` network plugin uses `ebtables` to set up some [dedup rules](https://github.com/kubernetes/kubernetes/blob/0480917b552be33e2dba47386e51decb1a211df6/pkg/kubelet/network/kubenet/kubenet_linux.go#L808). `ebtables` tries to automatically load missing `ebt_*` kernel modules when first used. Without access to `/lib/modules` this fails and `kubenet` subsequently fails to ensure the ebtables rules.
This PR replaces #2565
=> Allow kubelet to load missing kernel modules

coreos-base/oem-cloudsigma/files/cloud-config.yml, coreos-base/oem-rackspace/files/cloud-config.yml
etcd v0 has been removed from Container Linux.
=> coreos-base/oem-{cloudsigma,rackspace}: drop etcd.service drop-in

coreos-base/oem-vagrant-virtualbox/files/box/Vagrantfile, coreos-base/oem-vagrant-virtualbox/files/box/base_mac.rb, coreos-base/oem-vagrant-virtualbox/files/box/change_host_name.rb, coreos-base/oem-vagrant-virtualbox/files/box/configure_networks.rb, coreos-base/oem-vagrant-virtualbox/files/grub.cfg, coreos-base/oem-vagrant-virtualbox/metadata.xml, coreos-base/oem-vagrant-virtualbox/oem-vagrant-virtualbox-0.0.1.ebuild
This commit adds the new oem-vagrant-virtualbox provider, which is a
stripped down version of oem-vagrant for use with virtualbox and ignition.
It also sets the oem id to virtualbox instead of vagrant so it can be
handled correctly by ignition.
=> coreos-base: Add oem-vagrant-virtualbox

coreos-base/oem-virtualbox/files/grub.cfg, coreos-base/oem-virtualbox/files/oem-release, coreos-base/oem-virtualbox/metadata.xml, coreos-base/oem-virtualbox/oem-virtualbox-0.0.1.ebuild
This commit adds the oem-virtualbox package, which sets the id
in grub.cfg to "virtualbox" and creates an oem-release file
for virtualbox builds.
=> coreos-base: Add oem-virtualbox package

coreos-base/coreos-metadata/files/coreos-metadata-sshkeys@.service
An earlier commit modified the coreos-metadata.service unit to use the
COREOS_METADATA_OPT_PROVIDER environment variable to specify the
provider for coreos-metadata. That commit failed to make the same change
to the coreos-metadata-sshkeys@.service unit. This commit fixes this.
Fixes https://github.com/coreos/bugs/issues/2014
=> coreos-base/coreos-metadata: use $COREOS_METADATA_OPT_PROVIDER for ssh

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
The stable arm64 Perl ebuild is a version behind (as usual), so this bumps it for CVE-2017-6512.
Part of coreos/portage-stable#556.
=> profiles: sync with Perl 5.24 on arm64

coreos-base/oem-vagrant-virtualbox/files/grub.cfg, coreos-base/oem-vagrant-virtualbox/oem-vagrant-virtualbox-0.0.2.ebuild
This changes vagrant-virtualbox's oem-id from "virtualbox" to "vagrant-virtualbox"
to allow for more flexibility for this oem and add coreos-metadata support
for this oem.
Depends on https://github.com/coreos/ignition/pull/402
=> oem-vagrant-virtualbox: change vagrant-virtualbox's oem-id to "vagrant-virtualbox"

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.unmask
Drop a few obsolete version references noticed in coreos/portage-stable#569.
=> Profile cleanup

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.use
To allow a version patched for CVE-2017-1000117
Part of https://github.com/coreos/portage-stable/pull/571
=> profiles: bump git

profiles/coreos/arm64/package.accept_keywords
Part of coreos/portage-stable#576.
=> profiles: sync bzip2 on arm64 for GLSAs

sys-kernel/coreos-kernel/coreos-kernel-4.12.8-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.12.8-r1.ebuild
Add vmlinux, unstripped modules, and vdso binaries to `/usr/lib/debug` so they are available in the binpkgs.  This shouldn't affect the SDK or OS images, but costs about 350 MB of additional binpkg size.
Addresses https://github.com/coreos/bugs/issues/1243.
=> sys-kernel/coreos-{modules,kernel}: add debug symbols to /usr/lib/debug

profiles/coreos/targets/sdk/package.accept_keywords
Given our tooling, such as kola and ore, interacts with AWS, it's also
handy to have the awscli laying around to do things like emergency
cleanup, misc bash scripting, and other poking around.
This does add the yet-unused `profiles/coreos/targets/sdk/package.accept_keywords` file because that seemed like an appropriate place to accept the aws cli. Maybe there's a reason it wasn't used or that I should prefer something else?
Part of https://github.com/coreos/portage-stable/pull/580
=> profiles: accept awscli for the sdk

app-emulation/rkt/rkt-9999.ebuild
This just updates the GitHub name to bring it on par with the RHEL package.  It shouldn't affect anything, so I didn't bump the ebuild version.
I don't think we want to make this change in the manifest repo, since that will requires adding repo `--force-sync` flags in mantle for sharing Jenkins workspaces between builds from different channels (unless that change is backported to all active branches).
=> app-emulation/rkt: Correct the project name

profiles/coreos/arm64/package.accept_keywords
Accompanies https://github.com/coreos/portage-stable/pull/584
=> profiles/coreos: accept newer tcpdump for arm

coreos-base/oem-oracle-oci/files/iptables-rules, coreos-base/oem-oracle-oci/files/units/oracle-oci-iptables.service, coreos-base/oem-oracle-oci/oem-oracle-oci-0.2.0.ebuild
Prevent non-root users from accessing certain link-local services per [Oracle recommendation](https://docs.us-phoenix-1.oraclecloud.com/Content/Compute/References/bestpracticescompute.htm#two). Also apply filters to IP-forwarded virtual interfaces.
=> coreos-base/oem-oracle-oci: add link-local iptables rules

profiles/coreos/base/package.mask
This just masks newer versions instead of reverting the new ebuilds to make testing easier.
=> profiles: Block binutils upgrades

profiles/coreos/arm64/package.accept_keywords
Part of coreos/portage-stable#590
=> profiles: Sync libpcre on arm64 for GLSAs

profiles/coreos/arm64/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/595.  Fixes CVE-2017-13089 and CVE-2017-13090.
=> profiles: accept wget-1.19.1-r2 for arm64

README.md
- Point to portage-stable for packages we don't change.
- Point out important packages sdk-depends and coreos
=> readme: update readme to be more useful

profiles/coreos/base/package.use
This will enable us to emerge man-db without pulling in a ton of perl
dependencies. This means we can also switch to only having one man
provider.
=> profiles: add -nls for man-db

profiles/coreos/arm64/package.accept_keywords
Part of coreos/portage-stable#614
=> profiles: Bump libxml2 on arm64 for a GLSA

profiles/coreos/arm64/package.use.force
We do not use udev-init-scripts. Remove configuration for it.
cc @glevand: this was added in b37d1376cd13290ea708bd2e8a17dcce5e87064a. Do you know why? Were we including that package then?
=> profiles/arm64: remove ref to udev-init-scripts

net-fs/nfs-utils/files/nfs-utils-1.3.2-rpcbind-after.patch, net-fs/nfs-utils/nfs-utils-1.3.2-r11.ebuild
Make rpcbind an After= for nfs-mountd. This is fixed upstream but
hasn't been marked as stable on amd64/arm64 by gentoo. Should fix the
nfs races in kola tests.
=> net-fs/nfs-utils: fix rpcbind race

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of coreos/portage-stable#629
=> profiles: Sync the multipath-tools version on arm64

sys-kernel/coreos-kernel/coreos-kernel-4.14.8-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.14.8-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.14.8-r1.ebuild
GNU patch apparently doesn't set permissions when creating files.
=> sys-kernel/coreos-sources: make sure sync-check.sh is executable

sys-kernel/coreos-kernel/coreos-kernel-4.14.7-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.14.7-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.14.7-r1.ebuild
GNU patch apparently doesn't set permissions when creating files.
=> sys-kernel/coreos-sources: make sure sync-check.sh is executable (1632)

app-emulation/rkt/rkt-9999.ebuild
As it is now it doesn't build because we ship systemd 236.
Update the version needed to >= 220, which is what rkt needs [[1]].
[1]: https://github.com/rkt/rkt/blob/v1.29.0/stage1/init/init.go#L417
=> app-emulation/rkt: update systemd required for host stage1

coreos-devel/board-packages/board-packages-0.0.1.ebuild, coreos-devel/sdk-depends/sdk-depends-0.0.1.ebuild, coreos-devel/sdk-extras/sdk-extras-0.0.1.ebuild, profiles/coreos/targets/sdk/package.accept_keywords
Add a metapackage like `sdk-depends` to track useful things we want in portage-stable or coreos-overlay, but aren't actually required for building an image. This list is currently incomplete.
The end goal is for every package in `coreos-overlay` or `portage-stable` to be in, or be a dependency of something in `board-packages`, `sdk-depends`, or `sdk-extras`. This will make maintainence of those repos easier.
=> coreos-devel: add sdk-extras

net-misc/google-cloud-sdk/google-cloud-sdk-138.0.0-r1.ebuild
pyopenssl is needed for gsutil signurl.
Depends on https://github.com/coreos/portage-stable/pull/644
=> net-misc/google-cloud-sdk: depend on pyopenssl

app-emulation/containerd/containerd-1.0.0.ebuild, app-emulation/containerd/containerd-9999.ebuild
The old entries were for the release archives, which apparently worked at one point, since they're the versions that were downloaded into our source mirror.  This changes the entries to use the commit archives instead, which just have different parent directories.
=> app-emulation/containerd: Fix the 1.0.* manifest entries

app-emulation/containerd/containerd-9999.ebuild
A call to coreos-go_src_prepare in src_prepare will get go_export called, which exports the correct GOARCH value.
Fixes https://github.com/coreos/bugs/issues/2366 (torcx store has archives of wrong arch).
=> app-emulation/containerd: Fix GOARCH build problem

app-emulation/containerd/containerd-1.0.0.ebuild, app-emulation/containerd/containerd-9999.ebuild
The Docker tests won't match an abbreviated commit ID.
=> app-emulation/containerd: Specify the full commit SHA-1

profiles/coreos/targets/sdk/make.defaults
This profile is used by catalyst when building toolchains packages, which randomly fail from ccache permissions problems after certain releases.
An alternative solution is to create a separate profile just for catalyst, but that doesn't seem necessary given that there aren't many SDK packages that would benefit from this caching that aren't able to be tested on the amd64-usr board, which still has ccache.
Part of coreos/scripts#795
=> profiles: Disable ccache for SDK packages

app-emulation/containerd/containerd-9999.ebuild
Previously, containerd 1.0.1 was never built in beta so this wasn't needed, but since the Docker 17.12.1 LTS release was backported, it updated containerd to the affected version.
Backports #3084
=> Fix containerd 1.0.1 cross-compilation in beta

profiles/coreos/base/package.accept_keywords
Part of coreos/portage-stable#649
=> profiles: Drop obsolete util-linux entry

profiles/coreos/amd64/package.mask, profiles/coreos/base/package.accept_keywords
Part of coreos/portage-stable#650
=> profiles: Accept the fixed Intel microcode for Spectre mitigation

app-emulation/containerd/containerd-0.2.5-r3.ebuild
The URL would break building the torcx image if the mirrors have gone haywire.
=> app-emulation/containerd: Fix the 0.2.5 SRC_URI value

app-emulation/containerd/containerd-0.2.5-r3.ebuild
=> app-emulation/containerd: Fix the 0.2.5 SRC_URI value in alpha

app-emulation/containerd/containerd-0.2.5-r3.ebuild
=> app-emulation/containerd: Fix the 0.2.5 SRC_URI value in beta

profiles/coreos/arm64/package.accept_keywords
needed for https://github.com/coreos/portage-stable/pull/647
=> profiles/arm64: accept libudev-232

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.use.mask, profiles/coreos/targets/sdk/package.use
Goes along with https://github.com/coreos/portage-stable/pull/651
Newer versions of gnupg have an 'ssl' use flag, which is effectively the
same as the gnutls flag we already disabled.
This PR also enables 'usb' in addition to 'smartcard' for the sdk. Some
smartcards are also usb devices.
=> profiles/coreos: update gnupg use flags

profiles/coreos/base/package.accept_keywords
This isn't really necessary, but it syncs master with the newer change in beta.
Part of coreos/portage-stable#653
=> profiles: Drop special handling of intel-microcode

sys-kernel/coreos-sources/revbump.sh
master and alpha now carry multiple ebuilds.  Handle this by allowing the user to specify which ebuild to update.
=> sys-kernel/coreos-sources: allow specifying ebuild to revbump.sh

sys-kernel/coreos-kernel/coreos-kernel-4.14.30-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.14.30-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.14.30-r1.ebuild, sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.14/z0002-Add-arm64-coreos-verity-hash.patch, sys-kernel/coreos-sources/files/4.14/z0003-block-factor-out-__blkdev_issue_zero_pages.patch, sys-kernel/coreos-sources/files/4.14/z0004-block-cope-with-WRITE-ZEROES-failing-in-blkdev_issue.patch, sys-kernel/coreos-sources/files/4.14/z0005-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/4.14/z0006-net-don-t-call-update_pmtu-unconditionally.patch
Not fixing on 1729 since it won't promote to beta and 4.15 isn't affected.
=> sys-kernel/coreos-*: fix oops with vxlan

dev-libs/rustlib/rustlib-1.25.0.ebuild, eclass/coreos-cargo.eclass
In particular, this makes CI builds useful while reusing binary packages.
=> Automatically rebuild Rust projects when Rust is updated

sys-kernel/coreos-sources/coreos-sources-4.16.7.ebuild
The 4.16.x line and up now need flex and bison to build the kernel. Add
it here so people using our dev container will pick it up automatically.
=> sys-kernel/coreos-sources: add dep on bison, flex

profiles/coreos/base/package.mask
Part of coreos/portage-stable#661
=> profiles: Don't upgrade past Python 3.4 until profiles are updated

profiles/coreos/arm64/package.accept_keywords
Upstream has marked 1.19.5 as stable on arm64
Part of https://github.com/coreos/portage-stable/pull/662
=> profiles/arm64: remove wget accept

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/665.
=> profiles: drop obsolete git accepts

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/666.
=> profiles: drop obsolete git accepts for 1745

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/668.
=> profiles: drop obsolete git accepts for 1786

profiles/coreos/arm64/package.accept_keywords, profiles/coreos/base/package.accept_keywords
Part of https://github.com/coreos/portage-stable/pull/667.
=> profiles: drop obsolete git accepts for 1772

sys-kernel/coreos-kernel/coreos-kernel-4.14.47-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.14.47-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.14.47-r1.ebuild, sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.14/z0002-Add-arm64-coreos-verity-hash.patch, sys-kernel/coreos-sources/files/4.14/z0003-block-factor-out-__blkdev_issue_zero_pages.patch, sys-kernel/coreos-sources/files/4.14/z0004-block-cope-with-WRITE-ZEROES-failing-in-blkdev_issue.patch, sys-kernel/coreos-sources/files/4.14/z0005-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/4.14/z0006-Revert-random-use-a-different-mixing-algorithm-for-a.patch, sys-kernel/coreos-sources/files/4.14/z0007-Revert-random-fix-crng_ready-test.patch, sys-kernel/coreos-sources/files/4.14/z0008-Revert-xen-netfront-Fix-race-between-device-setup-an.patch
Upstream commit f599c64fdf7d9c108e8717fb04bc41c680120da4 introduced a
regression preventing setting jumbo frames on aws.
=> sys-kernel/*: fix mtu regression on aws for 1772

sys-kernel/coreos-kernel/coreos-kernel-4.16.13-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.16.13-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.16.13-r1.ebuild, sys-kernel/coreos-sources/files/4.16/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.16/z0002-Add-arm64-coreos-verity-hash.patch, sys-kernel/coreos-sources/files/4.16/z0003-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/4.16/z0004-Revert-random-use-a-different-mixing-algorithm-for-a.patch, sys-kernel/coreos-sources/files/4.16/z0005-Revert-random-fix-crng_ready-test.patch, sys-kernel/coreos-sources/files/4.16/z0006-Revert-xen-netfront-Fix-race-between-device-setup-an.patch
Upstream commit f599c64fdf7d9c108e8717fb04bc41c680120da4 introduced a
regression preventing setting jumbo frames on aws.
=> sys-kernel/*: fix mtu regression on aws for alpha

profiles/coreos/targets/generic/make.defaults
Fixes `build_image` warning:
/usr/share/git-core/templates/hooks/fsmonitor-watchman.sample: /usr/bin/perl does not exist
WARNING build_image: test_image_content: Failed #! check
=> profiles: mask git hook implemented in perl

sys-apps/portage/files/portage-2.3.8-file-update.patch, sys-apps/portage/portage-2.3.8-r1.ebuild
Testing this as a temporary alternative to #3311 until toolchains bootstrapping issues are solved.
=> sys-apps/portage: Support new file command output

sys-kernel/coreos-sources/revbump.sh
Newer patch files are no longer signed.  :disappointed:
=> sys-kernel/coreos-sources: don't fail revbump.sh on missing signature

profiles/coreos/targets/sdk/make.defaults
Since the kernel is no longer buildable for arm64, disable the QEMU targets that were used by dracut to create the arm64 initramfs.  Also disable LLVM's arm64 support to speed up SDK Rust builds.
(There is much more to be done for real arm64 removal; this is just to make our SDK builds faster until then.)
=> profiles: Disable arm64 support in QEMU and Rust

profiles/coreos/base/make.defaults, profiles/coreos/targets/sdk/package.unmask
Part of coreos/portage-stable#690
=> Fix SDK bootstrapping with new profiles

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.mask
Fixes CVE-2018-17456.
Part of https://github.com/coreos/portage-stable/pull/692.
=> profiles: accept Git 2.16.5 but nothing newer for stable

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.mask
Fixes CVE-2018-17456.
Part of https://github.com/coreos/portage-stable/pull/694.
=> profiles: accept Git 2.16.5 but nothing newer for alpha

profiles/coreos/base/package.accept_keywords, profiles/coreos/base/package.mask
Fixes CVE-2018-17456.
Part of https://github.com/coreos/portage-stable/pull/693.
=> profiles: accept Git 2.16.5 but nothing newer for beta

profiles/coreos/targets/sdk/package.use
No scripts depend on this (yet); it's just for manual checking.
=> profiles: Build rustfmt in the SDK

profiles/coreos/base/package.mask
Repeated OS builds started failing from partitioned loop devices never being removed after the 2.33 update.
=> profiles: Revert the last util-linux upgrade

profiles/coreos/base/package.mask
This might not have had the intended effect, so undo it until it is investigated further to avoid version changing noise in releases.
Reverts #3556
=> Revert "profiles: Revert the last util-linux upgrade"

sys-kernel/coreos-kernel/coreos-kernel-4.14.96-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.14.96-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.14.96-r1.ebuild, sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.14/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/4.14/z0003-posix-cpu-timers-Unbreak-timer-rearming.patch
Alpha and beta already have kernels with the fix.
Addresses https://github.com/coreos/bugs/issues/2549.
https://github.com/coreos/linux/pull/302
=> sys-kernel/coreos-sources: fix POSIX timer rearming for stable

app-torcx/docker/docker-18.06.ebuild, metadata/md5-cache/app-torcx/docker-18.06
This only updates the 18.06 image to match what upstream Docker and Fedora are using.  The 17.03 image always used a newer tini version than upstream (a commit just before 0.13.1), and the 1.12 image doesn't use tini at all.
Requires coreos/portage-stable#724
=> app-torcx/docker: Pin the latest image to its tini version

profiles/coreos/base/package.use, profiles/coreos/targets/generic/package.provided
Part of coreos/portage-stable#726
=> profiles: Use Python 3 for glib-utils

sys-kernel/coreos-kernel/coreos-kernel-4.19.57-r1.ebuild, sys-kernel/coreos-modules/coreos-modules-4.19.57-r1.ebuild, sys-kernel/coreos-sources/coreos-sources-4.19.57-r1.ebuild, sys-kernel/coreos-sources/files/4.19/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch, sys-kernel/coreos-sources/files/4.19/z0002-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch, sys-kernel/coreos-sources/files/4.19/z0003-net-netfilter-add-nf_conntrack_ipv4-compat-module-fo.patch, sys-kernel/coreos-sources/files/4.19/z0004-ovl-drop-test-for-upperdir-used-as-lowerdir.patch
https://github.com/coreos/linux/pull/339
=> sys-kernel/coreos-sources: fix overlayfs Docker breakage in 4.19.56+

profiles/coreos/targets/generic/oem-aci/package.provided
I don't know why this works. Any version older than the 2.7 version we
use works. Portage appears to be doing the opposite of what it should
be.
=> profiles/oem-aci: provide old python

profiles/coreos/targets/generic/oem-aci/package.provided
This ensures the gce agent ACI has python. For unknown reasons including
python-3.6.5 in package.provided causes both python 3.x and 2.x to be
removed but we still need 2.x.
I don't know why this works. Any version older than the 2.7 version we
use works. Portage appears to be doing the opposite of what it should
be.
=> [build-2191] profiles/oem-aci: provide old python

profiles/coreos/targets/generic/oem-aci/package.provided
This ensures the gce agent ACI has python. For unknown reasons including
python-3.6.5 in package.provided causes both python 3.x and 2.x to be
removed but we still need 2.x.
I don't know why this works. Any version older than the 2.7 version we
use works. Portage appears to be doing the opposite of what it should
be.
=> [build-2219] profiles/oem-aci: provide old python

profiles/coreos/targets/generic/oem-aci/package.provided
This ensures the gce agent ACI has python. For unknown reasons including
python-3.6.5 in package.provided causes both python 3.x and 2.x to be
removed but we still need 2.x.
I don't know why this works. Any version older than the 2.7 version we
use works. Portage appears to be doing the opposite of what it should
be.
=> [build-2247] profiles/oem-aci: provide old python
