coreos/coreos-overlay

app-emulation/rocket/rocket-0.2.0-r1.ebuild
app-emulation/rocket/rocket-9999.ebuild
dev-util/go-bindata/go-bindata-3.0.5-r1.ebuild

this is just an alpha for testing. Need rocket to mature more before having proper ebuild.

overlay: add rocket

---

coreos-base/oem-cloudsigma/files/cloud-config.yml
coreos-base/oem-cloudsigma/oem-cloudsigma-0.0.1.ebuild

Depends on https://github.com/coreos/coreos-cloudinit/pull/315.

coreos-base: add oem-cloudsigma

---

profiles/coreos/base/package.use
sys-apps/systemd/systemd-219.ebuild
sys-apps/systemd/systemd-9999.ebuild

Depends on https://github.com/coreos/coreos-overlay/pull/1112.

sys-apps/systemd: bump to v219

---

sys-apps/systemd/systemd-9999.ebuild

This reverts commit 7869b14e10a1c9036d3f7e076c894c8faa8ce8f4.

Revert "sys-apps/systemd: mark systemd-219 stable on amd64"

---

sys-apps/systemd/files/218-0004-timesyncd-enable-timesyncd-in-virtual-machines.patch
sys-apps/systemd/files/218-0005-network-add-UseNTP-DHCP-option.patch
sys-apps/systemd/files/219-0001-timesyncd-enable-timesyncd-in-virtual-machines.patch
sys-apps/systemd/files/219-0002-network-add-UseNTP-DHCP-option.patch
sys-apps/systemd/systemd-218-r6.ebuild
sys-apps/systemd/systemd-219-r1.ebuild
sys-apps/systemd/systemd-219.ebuild

Updates both 218 and 219, for now only 218 has been tested.

systemd: add UseNTP DHCP option for network configs

---

profiles/coreos/base/make.defaults

This reverts commit 8c1eed4d214ce7d7327c946341bf1a375d8186ac.

Revert "profiles: enable etcd protocols 1 and 2"

---

sys-apps/systemd/files/219-0003-nspawn-map-all-seccomp-filters-to-capabilities.patch
sys-apps/systemd/systemd-218-r7.ebuild
sys-apps/systemd/systemd-219-r2.ebuild

http://cgit.freedesktop.org/systemd/systemd/commit/?id=9a71b1122c6e49dd9227f82b2f53837c7ea13019
Fixes coreos/bugs#293

sys-apps/systemd: nspawn Map seccomp filters to caps

---

profiles/coreos/base/make.defaults

This reverts commit 00d4ac172234b3707455e6a084babef7f852137b.

Revert "Revert "profiles: enable etcd protocols 1 and 2""

---

sys-apps/systemd/files/218-0007-Treat-a-trailing-backslash-as-an-error.patch
sys-apps/systemd/systemd-218-r9.ebuild

fixes coreos/bugs#315. still testing this, please don't merge yet

sys-apps/systemd: backport fix for trailing space in unit hanging systemd

---

profiles/coreos/base/make.defaults

This reverts commit 7610638477ae8172816302504749d38d5b1ea4b7.

Revert "Revert "Revert "profiles: enable etcd protocols 1 and 2"""

---

profiles/coreos/base/make.defaults

This reverts commit 9a2fede012635008a78160ea98ad22dc18fd6c73.

profiles: enable etcd protocols 1 and 2

---

coreos-base/update_engine/update_engine-9999.ebuild

Signed-off-by: Geoff Levand <geoff@infradead.org>

update_engine: Add arm64 keyword to ebuild

---

profiles/coreos/base/package.accept_keywords

https://bugs.gentoo.org/show_bug.cgi?id=551832

profiles: update to openssl-1.0.1n

---

app-emulation/docker/docker-9999.ebuild
coreos-base/coreos/coreos-0.0.1.ebuild
coreos-devel/board-packages/board-packages-0.0.1.ebuild
eclass/coreos-kernel.eclass

Various fixes and updates, most related to arm64.

coreos-overlay: fixes and updates

---

coreos-base/coreos/coreos-0.0.1.ebuild
eclass/coreos-kernel.eclass
profiles/coreos/base/package.use

Some issues still to work out with tmpfiles and logind.

selinux: make selinux optional based on USE flags, disable for now.

---

profiles/coreos/base/package.accept_keywords

profiles: remove unneeded entries for openssl

---

coreos-base/oem-packet/files/cloud-config.yml
coreos-base/oem-packet/files/phone-home.sh
coreos-base/oem-packet/files/reset-interfaces.sh
coreos-base/oem-packet/oem-packet-0.0.1.ebuild

Feedback appreciated!  Also, let me know if there is a better way to do this PR.

Packet image OEM

---

profiles/categories
profiles/coreos/base/package.accept_keywords

Depends on https://github.com/coreos/portage-stable/pull/245.

profiles: enable rust

---

profiles/coreos/base/package.accept_keywords

Depends on https://github.com/coreos/portage-stable/pull/247

profiles: update man pages for better light reading

---

profiles/coreos/base/packages

profiles: temporarily add attr to @system set

---

app-admin/kubelet/files/0001-Plumb-linker-flags-through-from-the-Makefile.patch
app-admin/kubelet/kubelet-1.0.1.ebuild

Fixes https://github.com/coreos/bugs/issues/418.

app-admin/kubelet: add kubernetes kubelet

---

eclass/coreos-kernel.eclass
profiles/coreos/base/profile.bashrc

In short, use CCACHE_BASEDIR to get better use of the cache

Fixes to make better use of ccache

---

dev-lang/go/go-9999.ebuild

Add a new USE flag 'arm64-extras' to the go ebuild which will build and install
the needed arm64 package files that will allow the SDK to cross build for arm64
targets.
@marineam There are a lot of ways we could do this.  Let me know if you have any preferences, ideas, etc.

coreos-overlay: dev-lang/go: arm64 package support

---

coreos-base/oem-interoute/files/cloud-config.yml
coreos-base/oem-interoute/files/cloudstack-coreos-cloudinit
coreos-base/oem-interoute/files/cloudstack-set-guest-password
coreos-base/oem-interoute/files/cloudstack-ssh-key
coreos-base/oem-interoute/files/coreos-setup-environment
coreos-base/oem-interoute/files/oem-release
coreos-base/oem-interoute/oem-interoute-0.0.2.ebuild

This is the initial PR for interoute OEM build of CoreOS. It mainly combines cloudstack related files with vmtoolsd since we are based on VMware hypervisor. We also modified the way we expose network information into the environment file to make utilising our MPLS VPN network easier.

init commit of interoute oem files

---

sys-apps/systemd/systemd-9999.ebuild

This reverts commit bcbae73b149b30cf9760801fc59e0e3b66129f4a.

Revert "sys-apps/systemd: mark v225 unstable"

---

dev-lang/go/go-9999.ebuild

profiles/coreos: downgrade to go 1.4.2

---

dev-lang/go/go-1.4.3.ebuild
profiles/coreos/base/package.accept_keywords

https://github.com/golang/go/issues?q=milestone%3AGo1.4.3

dev-lang/go: bump to 1.4.3

---

app-admin/kubelet/files/0001-kubelet-report-NodeReady-last-in-status-list.patch
app-admin/kubelet/files/0002-explicitly-check-Ready-condition-in-validate-cluster.patch
app-admin/kubelet/files/0003-kubelet-check-node-condition-by-type-rather-than-by-.patch
app-admin/kubelet/files/0004-pkg-kubelet-force-NodeReady-condition-to-be-last-on-.patch
app-admin/kubelet/kubelet-1.1.2-r1.ebuild

Upstream ref: https://github.com/kubernetes/kubernetes/pull/18401

app-admin/kubelet: force NodeReady condition to be last on existing nodes

---

dev-libs/openssl/files/gentoo.config-1.0.2
dev-libs/openssl/openssl-1.0.2f-r1.ebuild
dev-libs/openssl/openssl-1.0.2f.ebuild
net-misc/openssh/openssh-7.1_p1-r4.ebuild
profiles/coreos/base/package.accept_keywords

Fixes https://github.com/coreos/bugs/issues/214

openssl: remove bindist restriction and enable ec algorithms

---

dev-libs/openssl/files/openssl-1.0.2g-parallel-build.patch
dev-libs/openssl/openssl-1.0.2g.ebuild

https://bugs.gentoo.org/show_bug.cgi?id=575548

dev-libs/openssl: bump to 1.0.2g

---

sys-block/open-iscsi/open-iscsi-2.0.873-r2.ebuild

Fix open-iscsi ebuild

---

app-emulation/wa-linux-agent/files/0001-fix-sudo-asking-for-password.patch
app-emulation/wa-linux-agent/wa-linux-agent-2.1.3-r1.ebuild

app-emulation/wa-linux-agent: backport sudoers fix

---

sys-libs/glibc/files/2.23/glibc-2.23-gshadow-handle-erange.patch
sys-libs/glibc/glibc-2.21-r4.ebuild

Fix segfaults when reading long lines from /etc/gshadow

---

app-admin/flannel/files/flanneld-rkt.service

Fix https://github.com/coreos/bugs/issues/1439 and https://github.com/coreos/bugs/issues/1436.

Fix flannel issues

---

profiles/coreos/arm64/package.accept_keywords

Depends on ~~https://github.com/coreos/coreos-overlay/pull/2050~~ and ~~https://github.com/coreos/portage-stable/pull/458~~.

profiles/arm64: Cleanup keywords

---

profiles/coreos/base/package.accept_keywords

profiles: accept unstable curl 7.50.2

---

sys-auth/sssd/files/tmpfiles.d/sssd.conf
sys-auth/sssd/sssd-1.13.1-r3.ebuild

fixes coreos/bugs#1604
cc @mjg59

sys-auth/sssd: move config permissions into tmpfiles

---

profiles/coreos/arm64/package.accept_keywords

This fixes today's Jenkins build failure.

profiles: fix GLSA 201611-01 (unzip) on arm64

---

sys-kernel/coreos-kernel/coreos-kernel-4.8.11-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.8.11-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.8.11-r1.ebuild
sys-kernel/coreos-sources/files/4.8/z0001-security-overlayfs-provide-copy-up-security-hook-for.patch
sys-kernel/coreos-sources/files/4.8/z0002-selinux-Implementation-for-inode_copy_up-hook.patch
sys-kernel/coreos-sources/files/4.8/z0003-security-overlayfs-Provide-security-hook-for-copy-up.patch
sys-kernel/coreos-sources/files/4.8/z0004-selinux-Implementation-for-inode_copy_up_xattr-hook.patch
sys-kernel/coreos-sources/files/4.8/z0005-selinux-Pass-security-pointer-to-determine_inode_lab.patch
sys-kernel/coreos-sources/files/4.8/z0006-security-overlayfs-Provide-hook-to-correctly-label-n.patch
sys-kernel/coreos-sources/files/4.8/z0007-selinux-Implement-dentry_create_files_as-hook.patch
sys-kernel/coreos-sources/files/4.8/z0008-Add-secure_modules-call.patch
sys-kernel/coreos-sources/files/4.8/z0009-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch
sys-kernel/coreos-sources/files/4.8/z0010-x86-Lock-down-IO-port-access-when-module-security-is.patch
sys-kernel/coreos-sources/files/4.8/z0011-ACPI-Limit-access-to-custom_method.patch
sys-kernel/coreos-sources/files/4.8/z0012-asus-wmi-Restrict-debugfs-interface-when-module-load.patch
sys-kernel/coreos-sources/files/4.8/z0013-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch
sys-kernel/coreos-sources/files/4.8/z0014-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch
sys-kernel/coreos-sources/files/4.8/z0015-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch
sys-kernel/coreos-sources/files/4.8/z0016-x86-Restrict-MSR-access-when-module-loading-is-restr.patch
sys-kernel/coreos-sources/files/4.8/z0017-Add-option-to-automatically-enforce-module-signature.patch
sys-kernel/coreos-sources/files/4.8/z0018-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch
sys-kernel/coreos-sources/files/4.8/z0019-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.8/z0020-hibernate-Disable-in-a-signed-modules-environment.patch
sys-kernel/coreos-sources/files/4.8/z0021-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.8/z0022-crypto-rsa-Add-Makefile-dependencies-to-fix-parallel.patch

Add the patch from coreos/linux#29.

sys-kernel/coreos-{sources,modules,kernel}: fix random Jenkins failures

---

sys-kernel/coreos-kernel/coreos-kernel-4.7.3-r4.ebuild
sys-kernel/coreos-modules/coreos-modules-4.7.3-r4.ebuild
sys-kernel/coreos-sources/coreos-sources-4.7.3-r3.ebuild
sys-kernel/coreos-sources/files/4.7/z0001-Add-secure_modules-call.patch
sys-kernel/coreos-sources/files/4.7/z0002-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch
sys-kernel/coreos-sources/files/4.7/z0003-x86-Lock-down-IO-port-access-when-module-security-is.patch
sys-kernel/coreos-sources/files/4.7/z0004-ACPI-Limit-access-to-custom_method.patch
sys-kernel/coreos-sources/files/4.7/z0005-asus-wmi-Restrict-debugfs-interface-when-module-load.patch
sys-kernel/coreos-sources/files/4.7/z0006-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch
sys-kernel/coreos-sources/files/4.7/z0007-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch
sys-kernel/coreos-sources/files/4.7/z0008-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch
sys-kernel/coreos-sources/files/4.7/z0009-x86-Restrict-MSR-access-when-module-loading-is-restr.patch
sys-kernel/coreos-sources/files/4.7/z0010-Add-option-to-automatically-enforce-module-signature.patch
sys-kernel/coreos-sources/files/4.7/z0011-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch
sys-kernel/coreos-sources/files/4.7/z0012-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.7/z0013-hibernate-Disable-in-a-signed-modules-environment.patch
sys-kernel/coreos-sources/files/4.7/z0014-Security-Provide-copy-up-security-hooks-for-unioned-.patch
sys-kernel/coreos-sources/files/4.7/z0015-Overlayfs-Use-copy-up-security-hooks.patch
sys-kernel/coreos-sources/files/4.7/z0016-SELinux-Stub-in-copy-up-handling.patch
sys-kernel/coreos-sources/files/4.7/z0017-SELinux-Handle-opening-of-a-unioned-file.patch
sys-kernel/coreos-sources/files/4.7/z0018-SELinux-Check-against-union-label-for-file-operation.patch
sys-kernel/coreos-sources/files/4.7/z0019-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.7/z0020-Don-t-verify-write-permissions-on-lower-inodes-on-ov.patch
sys-kernel/coreos-sources/files/4.7/z0021-mm-remove-gup_flags-FOLL_WRITE-games-from-__get_user.patch
sys-kernel/coreos-sources/files/4.7/z0022-packet-fix-race-condition-in-packet_set_ring.patch

sys-kernel/*: patch af_packet race

---

profiles/coreos/arm64/package.accept_keywords

This depends on coreos/portage-stable#500.

Update to Python 2.7.12

---

sys-libs/glibc/files/2.23/glibc-2.23-pthread-use-after-free.patch
sys-libs/glibc/glibc-2.22-r5.ebuild

sys-libs/glibc: avoid use-after-free in pthread

---

profiles/coreos/arm64/package.accept_keywords
profiles/coreos/base/package.accept_keywords

Also drop an entry from base which is no longer needed.

profiles: accept curl-7.52.1-r1 on arm64

---

app-emulation/runc/files/0002-Dont-set-label-for-mqueue-under-userns.patch
app-emulation/runc/runc-1.0.0_rc2-r3.ebuild

app-emulation/runc: workaround userns issue

---

coreos/config/env/net-analyzer/tcpdump
profiles/coreos/arm64/package.accept_keywords

This is part of coreos/portage-stable#525.

Fix some recent GLSAs

---

sys-kernel/coreos-kernel/coreos-kernel-4.8.17-r3.ebuild
sys-kernel/coreos-modules/coreos-modules-4.8.17-r3.ebuild
sys-kernel/coreos-sources/coreos-sources-4.8.17-r3.ebuild
sys-kernel/coreos-sources/files/4.8/z0001-security-overlayfs-provide-copy-up-security-hook-for.patch
sys-kernel/coreos-sources/files/4.8/z0002-selinux-Implementation-for-inode_copy_up-hook.patch
sys-kernel/coreos-sources/files/4.8/z0003-security-overlayfs-Provide-security-hook-for-copy-up.patch
sys-kernel/coreos-sources/files/4.8/z0004-selinux-Implementation-for-inode_copy_up_xattr-hook.patch
sys-kernel/coreos-sources/files/4.8/z0005-selinux-Pass-security-pointer-to-determine_inode_lab.patch
sys-kernel/coreos-sources/files/4.8/z0006-security-overlayfs-Provide-hook-to-correctly-label-n.patch
sys-kernel/coreos-sources/files/4.8/z0007-selinux-Implement-dentry_create_files_as-hook.patch
sys-kernel/coreos-sources/files/4.8/z0008-Add-secure_modules-call.patch
sys-kernel/coreos-sources/files/4.8/z0009-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch
sys-kernel/coreos-sources/files/4.8/z0010-x86-Lock-down-IO-port-access-when-module-security-is.patch
sys-kernel/coreos-sources/files/4.8/z0011-ACPI-Limit-access-to-custom_method.patch
sys-kernel/coreos-sources/files/4.8/z0012-asus-wmi-Restrict-debugfs-interface-when-module-load.patch
sys-kernel/coreos-sources/files/4.8/z0013-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch
sys-kernel/coreos-sources/files/4.8/z0014-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch
sys-kernel/coreos-sources/files/4.8/z0015-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch
sys-kernel/coreos-sources/files/4.8/z0016-x86-Restrict-MSR-access-when-module-loading-is-restr.patch
sys-kernel/coreos-sources/files/4.8/z0017-Add-option-to-automatically-enforce-module-signature.patch
sys-kernel/coreos-sources/files/4.8/z0018-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch
sys-kernel/coreos-sources/files/4.8/z0019-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.8/z0020-hibernate-Disable-in-a-signed-modules-environment.patch
sys-kernel/coreos-sources/files/4.8/z0021-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.8/z0022-Revert-tty-serial-8250-add-CON_CONSDEV-to-flags.patch
sys-kernel/coreos-sources/files/4.8/z0023-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.8/z0024-selinux-allow-context-mounts-on-tmpfs-ramfs-devpts-w.patch
sys-kernel/coreos-sources/files/4.8/z0025-dccp-fix-freeing-skb-too-early-for-IPV6_RECVPKTINFO.patch

Patch the DCCP CVE for beta

---

coreos-base/oem-packet/oem-packet-0.0.5.ebuild

oem-packet: Enable for arm64

---

sys-kernel/coreos-kernel/coreos-kernel-4.10.4-r1.ebuld
sys-kernel/coreos-modules/coreos-modules-4.10.4-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.10.4-r1.ebuild
sys-kernel/coreos-sources/files/4.10/z0001-Add-secure_modules-call.patch
sys-kernel/coreos-sources/files/4.10/z0002-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch
sys-kernel/coreos-sources/files/4.10/z0003-x86-Lock-down-IO-port-access-when-module-security-is.patch
sys-kernel/coreos-sources/files/4.10/z0004-ACPI-Limit-access-to-custom_method.patch
sys-kernel/coreos-sources/files/4.10/z0005-asus-wmi-Restrict-debugfs-interface-when-module-load.patch
sys-kernel/coreos-sources/files/4.10/z0006-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch
sys-kernel/coreos-sources/files/4.10/z0007-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch
sys-kernel/coreos-sources/files/4.10/z0008-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch
sys-kernel/coreos-sources/files/4.10/z0009-x86-Restrict-MSR-access-when-module-loading-is-restr.patch
sys-kernel/coreos-sources/files/4.10/z0010-Add-option-to-automatically-enforce-module-signature.patch
sys-kernel/coreos-sources/files/4.10/z0011-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch
sys-kernel/coreos-sources/files/4.10/z0012-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.10/z0013-hibernate-Disable-in-a-signed-modules-environment.patch
sys-kernel/coreos-sources/files/4.10/z0014-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.10/z0015-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.10/z0016-selinux-allow-context-mounts-on-tmpfs-ramfs-devpts-w.patch
sys-kernel/coreos-sources/files/4.10/z0017-xfrm_user-validate-XFRM_MSG_NEWAE-XFRMA_REPLAY_ESN_V.patch
sys-kernel/coreos-sources/files/4.10/z0018-xfrm_user-validate-XFRM_MSG_NEWAE-incoming-ESN-size-.patch

sys-kernel/coreos-sources: apply fix for CVE-2017-7184

---

sys-kernel/coreos-kernel/coreos-kernel-4.10.4-r1.ebuld
sys-kernel/coreos-modules/coreos-modules-4.10.4-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.10.4-r1.ebuild
sys-kernel/coreos-sources/files/4.10/z0001-Add-secure_modules-call.patch
sys-kernel/coreos-sources/files/4.10/z0002-PCI-Lock-down-BAR-access-when-module-security-is-ena.patch
sys-kernel/coreos-sources/files/4.10/z0003-x86-Lock-down-IO-port-access-when-module-security-is.patch
sys-kernel/coreos-sources/files/4.10/z0004-ACPI-Limit-access-to-custom_method.patch
sys-kernel/coreos-sources/files/4.10/z0005-asus-wmi-Restrict-debugfs-interface-when-module-load.patch
sys-kernel/coreos-sources/files/4.10/z0006-Restrict-dev-mem-and-dev-kmem-when-module-loading-is.patch
sys-kernel/coreos-sources/files/4.10/z0007-acpi-Ignore-acpi_rsdp-kernel-parameter-when-module-l.patch
sys-kernel/coreos-sources/files/4.10/z0008-kexec-Disable-at-runtime-if-the-kernel-enforces-modu.patch
sys-kernel/coreos-sources/files/4.10/z0009-x86-Restrict-MSR-access-when-module-loading-is-restr.patch
sys-kernel/coreos-sources/files/4.10/z0010-Add-option-to-automatically-enforce-module-signature.patch
sys-kernel/coreos-sources/files/4.10/z0011-efi-Make-EFI_SECURE_BOOT_SIG_ENFORCE-depend-on-EFI.patch
sys-kernel/coreos-sources/files/4.10/z0012-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.10/z0013-hibernate-Disable-in-a-signed-modules-environment.patch
sys-kernel/coreos-sources/files/4.10/z0014-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.10/z0015-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.10/z0016-selinux-allow-context-mounts-on-tmpfs-ramfs-devpts-w.patch
sys-kernel/coreos-sources/files/4.10/z0017-xfrm_user-validate-XFRM_MSG_NEWAE-XFRMA_REPLAY_ESN_V.patch
sys-kernel/coreos-sources/files/4.10/z0018-xfrm_user-validate-XFRM_MSG_NEWAE-incoming-ESN-size-.patch

To round out the set of patches, apply it to master too.

sys-kernel/coreos-sources: apply patch for CVE-2017-7184

---

profiles/coreos/base/package.accept_keywords

Part of coreos/portage-stable#542.

profiles: bump curl

---

profiles/coreos/arm64/package.accept_keywords

Part of coreos/portage-stable#552.

profiles: sync Git version on arm64

---

app-admin/flannel-wrapper/files/flannel-docker-opts.service
app-admin/flannel-wrapper/files/flanneld.service
app-admin/flannel-wrapper/flannel-wrapper-0.7.1-r1.ebuild
app-admin/flannel-wrapper/metadata.xml
coreos-base/coreos/coreos-0.0.1.ebuild

Also adds missing ebuild metadata.

Reenable flannel on arm64

---

app-admin/kubelet-wrapper/files/kubelet-wrapper

Forward-port of https://github.com/coreos/coreos-overlay/pull/2535 to 1409.

Revert "Merge pull request #2308 from sapcc/master"

---

profiles/coreos/arm64/package.accept_keywords

Part of coreos/portage-stable#560

profiles: sync arm64 packages

---

profiles/coreos/base/package.use.mask
profiles/coreos/targets/sdk/package.use.mask

This is an alternative to coreos/scripts#704.

profiles: disable smartcard in gnupg for the boards

---

profiles/coreos/arm64/package.accept_keywords

Part of coreos/portage-stable#562.

profiles: sync man-db version on arm64

---

sys-kernel/coreos-kernel/coreos-kernel-4.12.4-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.12.4-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.12.4-r1.ebuild
sys-kernel/coreos-sources/files/4.12/z0001-efi-Add-EFI_SECURE_BOOT-bit.patch
sys-kernel/coreos-sources/files/4.12/z0002-Add-the-ability-to-lock-down-access-to-the-running-k.patch
sys-kernel/coreos-sources/files/4.12/z0003-efi-Lock-down-the-kernel-if-booted-in-secure-boot-mo.patch
sys-kernel/coreos-sources/files/4.12/z0004-Enforce-module-signatures-if-the-kernel-is-locked-do.patch
sys-kernel/coreos-sources/files/4.12/z0005-Restrict-dev-mem-and-dev-kmem-when-the-kernel-is-loc.patch
sys-kernel/coreos-sources/files/4.12/z0006-kexec-Disable-at-runtime-if-the-kernel-is-locked-dow.patch
sys-kernel/coreos-sources/files/4.12/z0007-Copy-secure_boot-flag-in-boot-params-across-kexec-re.patch
sys-kernel/coreos-sources/files/4.12/z0008-kexec_file-Disable-at-runtime-if-securelevel-has-bee.patch
sys-kernel/coreos-sources/files/4.12/z0009-hibernate-Disable-when-the-kernel-is-locked-down.patch
sys-kernel/coreos-sources/files/4.12/z0010-uswsusp-Disable-when-the-kernel-is-locked-down.patch
sys-kernel/coreos-sources/files/4.12/z0011-PCI-Lock-down-BAR-access-when-the-kernel-is-locked-d.patch
sys-kernel/coreos-sources/files/4.12/z0012-x86-Lock-down-IO-port-access-when-the-kernel-is-lock.patch
sys-kernel/coreos-sources/files/4.12/z0013-x86-Restrict-MSR-access-when-the-kernel-is-locked-do.patch
sys-kernel/coreos-sources/files/4.12/z0014-asus-wmi-Restrict-debugfs-interface-when-the-kernel-.patch
sys-kernel/coreos-sources/files/4.12/z0015-ACPI-Limit-access-to-custom_method-when-the-kernel-i.patch
sys-kernel/coreos-sources/files/4.12/z0016-acpi-Ignore-acpi_rsdp-kernel-param-when-the-kernel-h.patch
sys-kernel/coreos-sources/files/4.12/z0017-acpi-Disable-ACPI-table-override-if-the-kernel-is-lo.patch
sys-kernel/coreos-sources/files/4.12/z0018-acpi-Disable-APEI-error-injection-if-the-kernel-is-l.patch
sys-kernel/coreos-sources/files/4.12/z0019-bpf-Restrict-kernel-image-access-functions-when-the-.patch
sys-kernel/coreos-sources/files/4.12/z0020-scsi-Lock-down-the-eata-driver.patch
sys-kernel/coreos-sources/files/4.12/z0021-Prohibit-PCMCIA-CIS-storage-when-the-kernel-is-locke.patch
sys-kernel/coreos-sources/files/4.12/z0022-Lock-down-TIOCSSERIAL.patch
sys-kernel/coreos-sources/files/4.12/z0023-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.12/z0024-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.12/z0025-bonding-commit-link-status-change-after-propose.patch
sys-kernel/coreos-sources/files/4.12/z0026-virtio_net-fix-truesize-for-mergeable-buffers.patch

See https://github.com/coreos/bugs/issues/2076

sys-kernel/coreos-*: fix virtio net truesize

---

profiles/coreos/arm64/package.accept_keywords
profiles/coreos/base/package.use

Part of coreos/portage-stable#570.

Support installing repoman

---

dev-libs/rustlib/rustlib-1.19.0-r1.ebuild
eclass/coreos-cargo.eclass

This changes the rustc wrapper script to actually use cargo's RUSTC_WRAPPER variable, and the logic in the script now uses the --target option to detect when it is cross-compiling.  If it is, it transparently adds the --sysroot option to the rustc command so the target libraries are used in the board as its sysroot.  This allows dropping any distinction between host-compatible targets.
In doing this, the cross-compiler wrapper scripts had to be moved from the rustlib package to the eclass for all builds, since no longer having a --sysroot on every call would resurrect failures due to LD_LIBRARY_PATH.
The rustlib package itself is now also building proc_macro, using its target output directory in the library search path to find the bootstrapping libraries as it is building them.

eclass/coreos-cargo: Restructure how base libs are built

---

profiles/coreos/base/package.accept_keywords

Remove configuration for removed packages.

profiles/base: cleanup config for removed packages

---

profiles/coreos/base/package.accept_keywords
profiles/coreos/base/package.use
profiles/coreos/targets/generic/package.accept_keywords
profiles/coreos/targets/generic/package.use
profiles/coreos/targets/sdk/package.use

These packages no longer exist.
This probably isn't exhaustive.

profiles: cleanup package directives

---

profiles/coreos/targets/sdk/make.defaults

Part of coreos/scripts#796, backports #3105

Disable ccache for SDK packages in alpha

---

profiles/coreos/targets/sdk/make.defaults

Part of coreos/scripts#797, backports #3105

Disable ccache for SDK packages in beta

---

sys-kernel/coreos-kernel/coreos-kernel-4.14.44-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.14.44-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.14.44-r1.ebuild
sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.14/z0002-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.14/z0003-block-factor-out-__blkdev_issue_zero_pages.patch
sys-kernel/coreos-sources/files/4.14/z0004-block-cope-with-WRITE-ZEROES-failing-in-blkdev_issue.patch
sys-kernel/coreos-sources/files/4.14/z0005-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
sys-kernel/coreos-sources/files/4.14/z0006-Revert-random-use-a-different-mixing-algorithm-for-a.patch
sys-kernel/coreos-sources/files/4.14/z0007-Revert-random-fix-crng_ready-test.patch
sys-kernel/coreos-sources/files/4.14/z0008-Revert-xen-netfront-Fix-race-between-device-setup-an.patch

Upstream commit f599c64fdf7d9c108e8717fb04bc41c680120da4 introduced a
regression preventing setting jumbo frames on aws.

sys-kernel/*: fix mtu regression on aws for stable

---

sys-kernel/coreos-kernel/coreos-kernel-4.14.48-r1.ebuild
sys-kernel/coreos-kernel/coreos-kernel-4.16.14-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.14.48-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.16.14-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.14.48-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.16.14-r1.ebuild
sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.14/z0002-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.14/z0003-block-factor-out-__blkdev_issue_zero_pages.patch
sys-kernel/coreos-sources/files/4.14/z0004-block-cope-with-WRITE-ZEROES-failing-in-blkdev_issue.patch
sys-kernel/coreos-sources/files/4.14/z0005-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
sys-kernel/coreos-sources/files/4.14/z0006-Revert-random-use-a-different-mixing-algorithm-for-a.patch
sys-kernel/coreos-sources/files/4.14/z0007-Revert-random-fix-crng_ready-test.patch
sys-kernel/coreos-sources/files/4.14/z0008-Revert-xen-netfront-Fix-race-between-device-setup-an.patch
sys-kernel/coreos-sources/files/4.14/z0009-hv_netvsc-Fix-a-network-regression-after-ifdown-ifup.patch
sys-kernel/coreos-sources/files/4.16/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.16/z0002-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.16/z0003-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
sys-kernel/coreos-sources/files/4.16/z0004-Revert-random-use-a-different-mixing-algorithm-for-a.patch
sys-kernel/coreos-sources/files/4.16/z0005-Revert-random-fix-crng_ready-test.patch
sys-kernel/coreos-sources/files/4.16/z0006-Revert-xen-netfront-Fix-race-between-device-setup-an.patch
sys-kernel/coreos-sources/files/4.16/z0007-hv_netvsc-Fix-a-network-regression-after-ifdown-ifup.patch

Backport an Azure network driver fix

---

sys-kernel/coreos-kernel/coreos-kernel-4.14.49-r1.ebuild
sys-kernel/coreos-modules/coreos-modules-4.14.49-r1.ebuild
sys-kernel/coreos-sources/coreos-sources-4.14.49-r1.ebuild
sys-kernel/coreos-sources/files/4.14/z0001-kbuild-derive-relative-path-for-KBUILD_SRC-from-CURD.patch
sys-kernel/coreos-sources/files/4.14/z0002-Add-arm64-coreos-verity-hash.patch
sys-kernel/coreos-sources/files/4.14/z0003-block-factor-out-__blkdev_issue_zero_pages.patch
sys-kernel/coreos-sources/files/4.14/z0004-block-cope-with-WRITE-ZEROES-failing-in-blkdev_issue.patch
sys-kernel/coreos-sources/files/4.14/z0005-tools-objtool-Makefile-Don-t-fail-on-fallthrough-wit.patch
sys-kernel/coreos-sources/files/4.14/z0006-Revert-random-use-a-different-mixing-algorithm-for-a.patch
sys-kernel/coreos-sources/files/4.14/z0007-Revert-random-fix-crng_ready-test.patch
sys-kernel/coreos-sources/files/4.14/z0008-Revert-xen-netfront-Fix-race-between-device-setup-an.patch
sys-kernel/coreos-sources/files/4.14/z0009-hv_netvsc-Fix-a-network-regression-after-ifdown-ifup.patch
sys-kernel/coreos-sources/files/4.14/z0010-Revert-tcp-avoid-integer-overflows-in-tcp_rcv_space_.patch

sys-kernel/coreos-sources: fix TCP window size issues for 1772

---

profiles/coreos/targets/sdk/package.unmask

Clean up profiles sync transitioning files

---

sys-auth/polkit/files/polkit-0.113-allow-uid-of-1-for-a-PolkitUnixProcess.patch
sys-auth/polkit/files/polkit-0.113-fix-CVE-2018-1116-Trusting-client-supplied-UID.patch
sys-auth/polkit/polkit-0.113-r5.ebuild

Part of https://github.com/coreos/portage-stable/pull/742.

sys-auth/polkit: fix CVE-2018-1116; fix CVE-2018-19788 fix

---

sys-apps/dbus/dbus-1.10.18-r1.ebuild
sys-apps/dbus/files/CVE-2019-12749.patch

https://www.openwall.com/lists/oss-security/2019/06/11/2

sys-apps/dbus: fix CVE-2019-12749
